### ISSUE TITLE
PDP6: @ LISP

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#100]
I tested @ LISP from Samsons DECtapes.  It doesn't work quite right, because typing doesn't echo properly.  It seems to work on @aap's PDP-6 simulator.

@ LISP is a PDP-6 program (from 1966-1967), so it could be some 6/10 incompatibility.  It also uses Microtape, but I don't think that affects typing.

**Comment by larsbrinkhoff** [comment]
The tapes are here: http://pdp-6.net/misc/samson_tapes.zip

@ LISP is on the "Subway" tape.

**Comment by larsbrinkhoff** [comment]
https://github.com/PDP-10/its/issues/1582

**Comment by rcornwell** [comment]
I believe this is fixed.

**Comment by larsbrinkhoff** [comment]
A simple test case is to type just about anything and see if it echoes.  `(CONS 1 2)` should return a result.

**Comment by rcornwell** [comment]
FSC passes KA10 diagnostics, the use of FSC is for a PDP6 only. I say we close this bug and if this is still a problem when I have the PDP6 released we can reopen it.

**Comment by larsbrinkhoff** [comment]
Ok.
