### ISSUE TITLE
KA10: Terminal echo delay with set line speed on DC10 multiplexer

### ISSUE THREAD

**Issue by pascalgp** [rcornwell/sims#101]
KA10: Terminal echo delay with line speed setting on DC10 multiplexer

In TOPS-10 6.03, when a line speed is specified on the DC multiplexer an intermittent but significant lag in echo occurs on character input (as when typing). The lag typically occurs after typing 2 or 3 characters, is in the 1 to 2 second range and observed at all line speeds. This behavior was introduced with the June 1 2018 commit 6464038c1360936716949421135c87ed5a7e4fb2

**Comment by rcornwell** [comment]
This is a sim_tmxr issue. There have been no changes to DC10 code in a long time.

@markpizz

**Comment by markpizz** [comment]
Without having a specific test configuration, I would suggest that you move the
```
sim_clock_coschedule(uptr, tmxr_poll);              /* continue poll */
```
to the bottom of the dc_svc() unit service routine.

This allows the complete state of the mux (which has just been changed by the execution of the dc_svc() routine) to be considered when scheduling the next poll.

**Comment by rcornwell** [comment]
I can try this. You should have a compete test setup, from the tmxr_rqln bug.

**Comment by pascalgp** [comment]
Moving the sim_clock_coschedule call in dc_svc to immediately before the return statement does alleviate the issue. There is better tolerance to steady input with lag occurring randomly every 10 to 20 characters or so.

**Comment by rcornwell** [comment]
I noticed that the characters delay seems to vary a bit.

**Comment by markpizz** [comment]
Well, all of the timing is based on the execution rate (consistent decrementing of sim_interval) and clock calibration.  This then gives the timing (in instructions) that the delay for each character's reception or transmission has.  Idling may cause some variance.  Try with and without idling.  There should never be any slamming of sim_interval to 0 (if that is logically necessary, then schedule an event to run now).

Multiple different simulators using completely different TMXR device implementations have been reliably measured to deliver output at rates from 110bps up to 19200bps with less than 1% variance of expected output rates.  Above 19200, the measurements get a little sloppier but still are reasonable.  These measurements were done with devices that had simulator programmatic speed settings (DZ, VH, 3b2's MUX) with one and more than one line running concurrently.  The DMA capable devices (VH and 3b2), when operating in DMA mode, deliver DMA sized bursts of data in a telnet connection, but the average delivery (and I/O completion time) is precisely at the programmed port speed.

**Comment by rcornwell** [comment]
sim_interval is only ever decremented. Sim_interval on the PDP10 simulator represents about 1 memory cycle. If this variance is acceptable I will move the line down and commit the changes.

**Comment by markpizz** [comment]
Consistent decrementing tracking memory references or instructions is reasonable and correct.  I only mentioned not setting sim_interval directly to 0 since I've seen that done (not necessarily by you) by some folks.

Moving the sim_activate_*() or sim_clock_coschedule() to the end of the service routine should be done on any unit service routine that uses the TMXR APIs.

**Comment by rcornwell** [comment]
sim_interval is only ever decremented. Sim_interval on the PDP10 simulator represents about 1 memory cycle. If this variance is acceptable I will move the line down and commit the changes.
