### ISSUE TITLE
KA10: WAITS display hardware devices

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#102]
Just pie in the sky for now.

But this is a good description:  
https://www.saildart.org/FACIL.TED[H,DOC]

**Comment by larsbrinkhoff** [comment]
To summarize, there were these devices:

- III vector displays.  A handful.
- Data Disc raster displays.  Many.
- Imlacs.  A handful.

These all used the SAIL keyboards.  I'm not sure whether the Imlacs were actually used for graphics.

**Comment by larsbrinkhoff** [comment]
I see @rcornwell has got started on the III display.

@markpizz, this is another case of a multiuser system with more than one graphical display.

I'm not saying there's any urgency here.  But I'd like to plant a seed for consideration.  I think one use case is running the emulator on a networked host.  Ideally users would connect and be able to see the display locally.  We have a special purpose program for this for the ITS Knight TV system, but I'm not sure it will generalize for all kinds of displays.  Maybe VNC or something similar would be an option.

**Comment by markpizz** [comment]
Extending the current model to more than one window is where this is going to start.  The fundamental model connects keyboard mouse and video through that window which move the keyboard and mouse as focus moves between windows.  Exporting windows beyond the local host machine is a much further reach and may not really be possible even if all of this happened across X- windows.  The challenge will be having a single application (simulator) connect to an arbitrary set of remote displays.  Driving an arbitrary set of X displays concurrently is a very different problem from an application that opens N different windows on the same display.

Meanwhile looking at what's been previously described about the imlac displays and the MTY devices that they connected to, it would seem that an imlac is merely a particular terminal emulator.  I know nothing about either of the others.

**Comment by larsbrinkhoff** [comment]
Yes, the Imlac is a stand alone computer with a display.  They were attached through serial lines, so this use case is well covered.

I do understand that multiple displays pose a problem and that some use cases may be outside the scope of SIMH.  I'm mostly trying to paint a picture of the problem space so we can plan for the future.  WAITS had six III displays and a bunch of DataDisc displays.  These were driven from two different controllers attached to the PDP-10 memory and I/O buses, so they are much more tightly tied to the processor than a serial line terminal.

**Comment by larsbrinkhoff** [comment]
@rcornwell, I'm adding some III stuff today.

**Comment by rcornwell** [comment]
You can just send me where to put what hooks if that is easier. I can add you into credits at top.

**Comment by larsbrinkhoff** [comment]
I don't think that's much easier actually.

**Comment by rcornwell** [comment]
The III display is now working. So I am closing this issue.

**Comment by larsbrinkhoff** [comment]
Can you post some screenshots?

**Comment by larsbrinkhoff** [comment]
```
<bgbaumgart> larsb: DD in section 6 of the FACIL.TED and HM files see all
+version in directory  https://www.saildart.org/[H,DOC]/

**Comment by larsbrinkhoff** [comment]
```
<bgbaumgart> kiteguy:Image #14 Black and Green raster, 480 by 512 pixels, 34
+lines of 85 charactersEach pixel is a single bit and can display exactly two
+colors: BLACK or GREEN. The raster has 480 rows of 512 columns, the normal
+font is a dot matrix, with 12 rows by 6 columns per glyph. The normal font
+size can display 34 lines of 85 characters per line. The
<bgbaumgart> Data Disc storage capacity could refresh 32 video channels at 30
+hertz.
<bgbaumgart> See URL at https://www.saildart.org/Visitor_1976/

**Comment by larsbrinkhoff** [comment]
Appendix 2 has information about DD displays.
https://stacks.stanford.edu/file/druid:hb976hq8639/uuomanual.pdf
