### ISSUE TITLE
PDP-6/KA10: Type 630 Data Communication

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#103]
Used by WAITS.

**Comment by larsbrinkhoff** [comment]
Diagram of SAIL PDP-6/10 hardware devices.  From @bgbaumgart's book.
![sail-hw](https://user-images.githubusercontent.com/775050/56388778-304bd200-6228-11e9-8597-df3ce0d69f62.png)

**Comment by rcornwell** [comment]
The type 630 is almost identical to the DC10.

**Comment by rcornwell** [comment]
Working under WAITS.
