### ISSUE TITLE
KA10: RMW cycles?

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#106]
When using the AUXCPU to share memory with @aap's PDP-6, I sometimes see memory errors.  Reading a location can termporarily show up as 0.  And when the processors write to the same location, there can be a bad result.

We think that fixing this *may* require having real read-modify-write cycles in both simulators.  Is this open for discussion?

**Comment by rcornwell** [comment]
I already support RMW cycles, if the modify flag is set to one the cycle is the write side of a RMW cycle.

**Comment by larsbrinkhoff** [comment]
I'm not sure about this, but I was thinking that reads and writes that go outside the simulator, such as through the AUXCPU device, would have to be handled specially with they were part of a modify cycle.

I see some code like this:

```
        if (Mem_read(0, 0, 0))
            goto last;
#if KI | KL | ITS | BBN
        modify = 1;
#endif
        AR = MB;
```

Here, the Mem_read happens first, *then* modify is set to 1.  So it looks like Mem_read can't know it's starting a modify cycle.

**Comment by rcornwell** [comment]
modify has meaning to the pager telling it that it should check for write access and fail if the location can't be written to. Modify is set whenever the instruction will write the same location that it read. I can move the modify before the Mem_read or make it a parameter to Mem_read. After the PDP6 mods are checked in I will move the modifies before the reads and verify that everything still works correctly.

**Comment by larsbrinkhoff** [comment]
Thanks, we can certainly looks at this later.  @aap made a change to his pdp6, and that made things work much better.

However, I think there's still a problem waiting to happen.  Consider this scenario:

1. The KA10 executes a RMW instruction.
2. It reads a words through AUXCPU.
3. The auxiliary CPU writes that word.
4. The KA10 writes back the result.

It shouldn't be too hard to fix if the "modify" bit is available to Mem_read.  Then AUXCPU can send along this information and the memory system in the other end can wait for the corresponding Mem_write.

**Comment by rcornwell** [comment]
I understand the problem, however not all read / write to the same location where RMW cycles. I will have to verify which ones are actually RMW and which are not.

**Comment by rcornwell** [comment]
modify should now reflect if the instruction will modify it's memory location or not.

**Comment by larsbrinkhoff** [comment]
I haven't checked this, but it's now used by the ITS build.
