### ISSUE TITLE
KA10: IDIV -2^35 / -1

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#109]
I believe there is a problem with IDIV -2<sup>35</sup>/-1.

First, as per documentation:

> If [...] AC contains -2<sup>35</sup> and the operand specified by M is -1 (except in the KS10), set Trap 1, Overflow, and No Divide, and go directly to the next instructions without affecting the original AC or memory operand in any way.

https://archive.org/details/bitsavers_decpdp1019_38003019/page/n63

Second, running on the LCM KA10 (TOPS-10):

```
.DEBUG TEST
LINK:   Loading
[LNKDEB DDT Execution]

START/  MOVSI 1,400000  
DDTEND+1/       SETO 2,0        
DDTEND+2/       IDIVM 1,2       
DDTEND+3/       JRST 4,0        .$B     

$G
$1B>>DDTEND+3   
1/      SETZ 0  
2/      -1      
```

But on the simulator (ITS):

```
100/   MOVSI 1,400000   
101/   SETO 2,   
102/   IDIVM 1,2   
103/   0   .$b   

100$g
$1B; 103>>0   0/   0   0/   0      
1/   SETZ   
2/   SETZ
```

**Comment by larsbrinkhoff** [comment]
I searched diagnostics to see if I could find a test of this particular corner case, but didn't find anything obvious.  I looked at DEC diagnostics files called DBKDAM ,DFKDAM, DSKAL, DBKALM, and one in ITS called MAINT; PART F.

**Comment by rcornwell** [comment]
KA diags are DAKxx DBKxx are for KI10. I am not sure that the KA had this issue. KA could not trap so this would be for KI or KL.

**Comment by larsbrinkhoff** [comment]
No Divide is also triggered by -2<sup>35</sup>/+1, according to ProcRefMan.  This goes for both KA and KI.

**Comment by rcornwell** [comment]
What does the diags say about this specific case?

**Comment by larsbrinkhoff** [comment]
I don't know my way around the diagnostics, but I'm keen to find out.  I'll let you know if I find anything.

**Comment by rcornwell** [comment]
Once I get FP working correct I will try and add this trap and see if diags complain.

**Comment by larsbrinkhoff** [comment]
Cool.

I believe DAKAL is the KA10 division diagnostics.  As far as I can see there's no check for a dividend -2<sup>35</sup> and divisor ±1.  I have looked around all IDIV and DVND in this file:

http://pdp-10.trailing-edge.com/klad_sources/01/klad.sources/dakalm.mac.html

**Comment by larsbrinkhoff** [comment]
(Side note: I tested IDIV -2<sup>35</sup>/-1 on @aap's PDP-6 simulator, and I got a 0 and no overflow.

**Comment by larsbrinkhoff** [comment]
I will try to update this table with results.

| Processor | Result | Flags
| --- | --- | ---
| PDP-6 | 0 |
| KA10 | - |
| KI10 |
| KL10 |
| KS10 |

**Comment by aap** [comment]
On drawing ARC2 you can see that IDIV will trigger an ARRT SH LT at ET2 in later revisions of the hardware, where older revisions only shift MQ. The AI drawings do not have this change yet so it most likely would not have given the overflow as KATIA does.

**Comment by rcornwell** [comment]
I checked the prints and do not see any test for IDIV other then zero. The 1973 Proc Manual only mentions divide by zero. Checking on KA for either BR =  4000000 or AR = 400000 results in diags failing to pass. DAKAL check test F14400, F14410, F7500. I think the later processor manual is wrong.

**Comment by larsbrinkhoff** [comment]
Well KA10 serial numver 175 does behave as per the 83 ProcRefMan.  So then maybe different individuals behaved differently depending on when they were made, or whether field service installed an update or not.

**Comment by larsbrinkhoff** [comment]
@aap, what did you see on drawing ARC2?  Can you translate to English?

@rcornwell, which version of the prints did you check, and which pages?

**Comment by larsbrinkhoff** [comment]
As far as I can see, test F14400 is -2<sup>35</sup> divided by 2, so it shouldn't fail.

**Comment by larsbrinkhoff** [comment]
F14410 loks like 4 / 0.  Do you have a version other than this one?  
http://pdp-10.trailing-edge.com/klad_sources/01/klad.sources/dbkal.seq.html

**Comment by larsbrinkhoff** [comment]
F7500 is 1 and 2 divided by -2<sup>35</sup>.  This is not the case I'm talking about.

I'm only talking about -2<sup>35</sup> divided by -1 or +1.  Nothing else.

**Comment by larsbrinkhoff** [comment]
I'm testing this patch:

```
diff --git a/PDP10/ka10_cpu.c b/PDP10/ka10_cpu.c
index 3522179..7961b73 100644
--- a/PDP10/ka10_cpu.c
+++ b/PDP10/ka10_cpu.c
@@ -3718,6 +3718,13 @@ fnorm:
                   break;              /* Done */
               }

+              if (AR == SMASK && (BR == 1 || BR == SMASK)) {
+                  FLAGS |= OVR|NODIV; /* Overflow and No Divide */
+                  sac_inh=1;          /* Don't touch AC */
+                  check_apr_irq();
+                  break;              /* Done */
+              }
+
               if (AR & SMASK) {
                  AR = (CM(AR) + 1) & FMASK;
                  flag1 = !flag1;

**Comment by rcornwell** [comment]
Does this test pass diags? Because I tried something very similar and it failed diags.

**Comment by larsbrinkhoff** [comment]
No, I haven't run diags yet.  I'm pondering how to run them.  Do you have like a bootable magtape image or something?

Or maybe I can make them run on ITS.

**Comment by larsbrinkhoff** [comment]
Should be `BR == FMASK`.

**Comment by rcornwell** [comment]
On entry to IDIVx AR = C(E), BR = C(A). 

There is a bootable diags image at sky-visions.com/dec/klad.

boot rpa0
klad:diamon

* DIAMON [DDQDC] - DECSYSTEM DIAGNOSTIC MONITOR - VER 0.15 *

DEV:T,K,D,V,P - p
DISK:[P,PN] - [6,10]

DIAMON CMD - d

FILE.EXT - ka.cmd

**Comment by rcornwell** [comment]
BR == FMASK check that BR == -1.

FMASK  is all one.
CMASK is all but sign bit
SMASK is sign bit only.

**Comment by larsbrinkhoff** [comment]
I get this from klad.rp6.  What am I missing?

```
sim> boot rpa0
BOOTS

klad:diamon
?

**Comment by rcornwell** [comment]
klad:diamon[6,10] works

**Comment by larsbrinkhoff** [comment]
Thanks.  Diags are running now.

I have this with no errors from DAKAL or anywhere else.

```
diff --git a/PDP10/ka10_cpu.c b/PDP10/ka10_cpu.c
index a08334d..6f9e1d9 100644
--- a/PDP10/ka10_cpu.c
+++ b/PDP10/ka10_cpu.c
@@ -4148,6 +4148,13 @@ left:
                   break;              /* Done */
               }

+              if (AR == SMASK && (BR == 1 || BR == FMASK)) {
+                  FLAGS |= OVR|NODIV; /* Overflow and No Divide */
+                  sac_inh=1;          /* Don't touch AC */
+                  check_apr_irq();
+                  break;              /* Done */
+              }
+
               if (AR & SMASK) {
                  AR = (CM(AR) + 1) & FMASK;
                  flag1 = !flag1;

**Comment by larsbrinkhoff** [comment]
Well, I get this in both versions:

```
DAKEB. 

PDP-10 KA10 REENTRANT RELIABILITY DIAGNOSTIC [DAKEB]
VERSION 0.2, SV=0.14, 60HZ

PC=  031465 
ERROR IN REENTRANT RELIABILITY DIAGNOSTIC - 
PROTECT INTERRUPT DURING A BLT INSTRUCTION
DATWRD= 774000 052000 
CONTENTS OF THE BLT POINTER AFTER THE INTERRUPT
BASE ADDRESS= 774000 776000 
RELOCATED ADDRESS= 046000 466000 
BLT TERMINATE ADDR= 776000 
TEST NUMBER= 6

**Comment by rcornwell** [comment]
I did not see any errors with the patch either... I will run TOPS10 tests to make sure it does not break Tops10. I will also do an ITS build to check that.

Yes I also get this error. It is something about BLT to NXM if I remember correctly. Or access outside of protected memory.

**Comment by larsbrinkhoff** [comment]
Great!  Possibly this isn't right for PDP6.  So maybe add `#if !PDP6` or something?

**Comment by rcornwell** [comment]
Ok can do that... have not run PDP6 diags on changes... KI diags seem to handle it.

**Comment by rcornwell** [comment]
I ran PDP6 diags and they passed... are you sure you are checking for correct values?

**Comment by larsbrinkhoff** [comment]
If KA10 diags are insensitive to this change, maybe PDP6 diags are too.  I have tested this from ITS, but I'll do another run to be extra sure.  I'll add a printf to the simulator.

**Comment by larsbrinkhoff** [comment]
Before:

```
100/   MOVSI 1,400000   
101/   SETO 2,   
102/   JRST 2,@103   
103/   104   
104/   IDIVM 1,2   
105/   JSP 3,106   
106/   .VALUE   

100$g
.VAL 0; 107>>0   0/   0   0/   0      
1/   SETZ   
2/   SETZ   
3/   10000,,106 
```

After:

```
100$g
.VAL 0; 107>>0   0/   0   0/   0      
1/   SETZ   
2/   -1   
3/   ANDCA 1,106   =410040000106   
```

**Comment by larsbrinkhoff** [comment]
The check for FMASK is not necessary, because BR is neagated if it was -1.  This is the latest version of my patch:

```
diff --git a/PDP10/ka10_cpu.c b/PDP10/ka10_cpu.c
index a08334d..e3b8fcf 100644
--- a/PDP10/ka10_cpu.c
+++ b/PDP10/ka10_cpu.c
@@ -4148,6 +4148,15 @@ left:
                   break;              /* Done */
               }

+#if !PDP6
+              if (AR == SMASK && BR == 1) {
+                  FLAGS |= OVR|NODIV; /* Overflow and No Divide */
+                  sac_inh=1;          /* Don't touch AC */
+                  check_apr_irq();
+                  break;              /* Done */
+              }
+#endif
+
               if (AR & SMASK) {
                  AR = (CM(AR) + 1) & FMASK;
                  flag1 = !flag1;

**Comment by rcornwell** [comment]
Ok... running tests on previous version to see if Mark's recent timer changes break anything.

**Comment by larsbrinkhoff** [comment]
- The 1968 "PDP-10 System Reference Manual" doesn't say anything about -2<sup>35</sup>/±1 on pages 2-29 or 2-30.
- The 1970 "KA10 CENTRAL PROCESSOR MAINTENANCE MANUAL" doesn't say anything in section 4.4.1.4.  But then, it doesn't say anything about dividing by zero either.
- The 1970 "PDP-10 REFERENCE HANDBOOK" doesn't say anything on pages 2-29 or 2-30.
- The 1973 "KI10 CENTRAL PROCESSOR MAINTENANCE MANUAL" says something on pages 8-11 and 8-12:
  > However should the original dividend be -2<sup>35</sup>, AR is not clear, and the result is positive when the divisor is ±1.  If the result of this initial subtraction is positive, DST2 sets Overflow and No Divide, and terminates the procedure so the processor goes on to the next instruction.  Dividing by zero is of course meaningless.  Placing a 1 in AR 35 allows use of -2<sup>35</sup> as a dividend, but it cannot be paired with a divisor of -1 because the result of 2<sup>35</sup> would be too large to accommodate in a single register.  (The prohibition on dividing -2<sup>35</sup> by +1 is just a happenstance of the logic.)

**Comment by larsbrinkhoff** [comment]
For the `#if PDP6` case:

IDIV -2<sup>35</sup>/-1 gives 0 as the quotient and 0 as the remainder.  No flags set.

Same for division by +1.  I guess the processor first takes the absolute value of the divisor like on a KA10.

-2<sup>35</sup>/0 does not touch the outputs, and sets Overflow.

**Comment by larsbrinkhoff** [comment]
Fixed in latest simulator and ITS.
