### ISSUE TITLE
KA10: Add PMP 3330 device to KA10 to support Waits.

### ISSUE THREAD

**Issue by rcornwell** [rcornwell/sims#11]

**Comment by b4** [comment]
See https://www.saildart.org/j5/sim.js https://www.saildart.org/j5/pdp10.js for a Javascript simulator implementing a portion of the controller.

**Comment by rcornwell** [comment]
See https://www.saildart.org/[H,DOC]/ FACIL.TED section 19 for full description of this device.

See sims/IBM360/ibm360_dasd.c for a implementation of a IBM 3330 disk drive.

**Comment by rcornwell** [comment]
Working under WAITS.
