### ISSUE TITLE
KA10: multiplication

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#110]
The ITS file MAINT; PART F.OLD has these checks:

```
5025/  MOVSI 12,400000
5026/  HRROI 11,777777
5027/  MUL 12,11
5030/  JOV 5032

5034/  MOVSI 12,400000
5035/  HRROI 11,777776
5036/  MUL 12,11
5037/  JOV 5041
```

There isn't solid evidence, but my assumption is that these checks are for a KA10.  The simulator fails these checks.  The simulator passes PART G.OLD and PART K.OLD.

**Comment by larsbrinkhoff** [comment]
The 82 ProcRefMan says:

> CAUTION
> 
> In the KA10, an AC operand of -2<sup>35</sup> is treated as though it were +2<sup>35</sup>, producing the incorrect sign in the product.

**Comment by larsbrinkhoff** [comment]
Testing on the LCM machines:

| CPU | Que pasa?
| --- | ---
| KA10 | Overflow
| KI10 |
| KL10 | **No overflow**
| KS10 | Overflow

**Comment by larsbrinkhoff** [comment]
Experimental results on the KA10:

| AC input | Memory intput | AC output | AC+1 output | Flag
| -- | -- | -- | -- | -- 
| 400000000000 | -2 | -2 | 400000000000 | Overflow
| 400000000000 | -1 | -1 | 400000000000 | Overflow
| 400000000000 | 0 | 0 | 0 | -
| 400000000000 | 1 | 1 | 0 | -
| 400000000000 | 2 | 2 | 0 | -

**Comment by larsbrinkhoff** [comment]
I think this passes DEC diagnostics.

```
diff --git a/PDP10/ka10_cpu.c b/PDP10/ka10_cpu.c
index e3b8fcf..a782438 100644
--- a/PDP10/ka10_cpu.c
+++ b/PDP10/ka10_cpu.c
@@ -4128,6 +4128,10 @@ left:
               }
               AR &= FMASK;
               MQ = (MQ & ~SMASK) | (AR & SMASK);
+#if KA
+              if (BR == SMASK && (AR & SMASK))  /* Handle special case */
+                 FLAGS |= OVR;
+#endif
               break;

     case 0230:       /* IDIV */

**Comment by larsbrinkhoff** [comment]
It also passes MAINT; PART F.OLD.

**Comment by rcornwell** [comment]
This patch is in current commit.

**Comment by larsbrinkhoff** [comment]
Fixed in latest simulator and ITS.
