### ISSUE TITLE
KI-10: (VMSER) Illegal memory reference at TTY initialization

### ISSUE THREAD

**Issue by pascalgp** [rcornwell/sims#112]
On the KI-10 with VMSER, getting this error after establishing a connection to a terminal:

```
?
?Can not get PFH?
?Ill mem ref at user PC 402234
```

The TTY is thereafter operational. The exception also occurs at startup on the console which prevents OPSER from launching. It appears to have been introduced with the June 7th paging changes.

**Comment by rcornwell** [comment]
Try the current commit. I fixed how the write flag is used in the pager.

**Comment by pascalgp** [comment]
This is addressed, thank you. Note that pdp10-ka will not build with this commit:

undefined reference to `pmp_dev'
