### ISSUE TITLE
KA10: Write headers to RH10/RP04

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#113]
ITS' Salvager program wants to write headers when formatting an RP04.  From a quick comparison between ka10_dp.c (which has the `set headers` command implemented) and ka10_rp.c this doesn't seem to be supported by the latter.

The Salvager finishes formatting but fails the verification:

    WORD 2521 OF CYLINDER 476 CORRECT 555555555753 ACTUAL 666666765555

**Comment by larsbrinkhoff** [comment]
Sorry, I was too quick.  ka10_rp.c should support headers.

**Comment by larsbrinkhoff** [comment]
Anyway, something seems off.  SALV writes these words to the disk:

```
RHWC:   726666666676            ;RP04 10-MODE WORST CASE PATTERN
        555555555753
        333333337266
        666666765555
        555557533333
        333372666666
        667655555555
        573333333333
```

So it looks like there's an offset by two words.

**Comment by larsbrinkhoff** [comment]
It seems SALV wants to write 202 (octal) words per sector, and the first two are the header words.

**Comment by larsbrinkhoff** [comment]
SALV uses command number 25, "write check headers", to format.  It then uses a plain 34, "read", to read data back and check against previously written data.

**Comment by larsbrinkhoff** [comment]
ITS only uses 2, 28, 30: seek, read data, write data.

**Comment by larsbrinkhoff** [comment]
This is what SALV writes to the header words.

```
        MOVSI A,%HRSER          ;GET DRIVE SERIAL NUMBER
        PUSHJ P,RHGET
         JRST RHMKER
        HRLZ D,A
        TLZ D,600000            ;FIRST "KEY" WORD IS SERIAL NO OF DRIVE FORMATTED ON
        HRR D,PKNUM(I)          ;SECOND "KEY" WORD IS I.T.S. PACK NUMBER
```

and

```
RHFMT0: MOVEI J,NCYLS+XCYLS
RHFMT1: SOJL J,RHFMT4           ;LOOP ON CYLINDERS
        MOVEI K,NHEDS
RHFMT2: SOJL K,RHFMT1           ;LOOP ON SURFACES
        MOVEI B,NSECS           ;ADJUST THE HEADER WORDS
        MOVEI C,0
RHFMT3: DPB J,[221100,,CYLBUF(C)]
        DPB K,[100500,,CYLBUF(C)]
```

This is what it reads:

```
        MOVE A,[%HRCTL,,SLVICWA_6+%HMRHD]
        PUSHJ P,RHSET
         JRST RESETL
        CONSO DSK,%HIDONE
         JRST .-1
        CONSZ DSK,%HIERR
         JRST RESETL
        HRRZ A,SLVIOWD+1                ;GET I.T.S. PACK NUMBER
        MOVEM A,PKNUM(I)
```

**Comment by larsbrinkhoff** [comment]
RP04 Device Control Logic User's Manual.

http://www.bitsavers.org/www.computer.museum.uq.edu.au/pdf/EK-RP04-OP-001%20RP04%20Device%20Control%20Logic%20User's%20Manual.pdf

**Comment by rcornwell** [comment]
Will add this either as part of KL10 or after release to simH

**Comment by larsbrinkhoff** [comment]
Workaround is to skip verification.

**Comment by larsbrinkhoff** [comment]
Here are some files for running SALV to format an RP04.

http://lars.nocrew.org/its/salv-rp04.zip
http://lars.nocrew.org/its/source%2blisting.zip

Steps:

1. pdp10-ka build/pdp10-ka/init.kl
2. At MAGDMP prompt, type l<ESC>ddt<CR>
3. It will echo strange, like "ldt".  Not to worry.
4. Next, type t<ESC>salv<CR
5. Now you're in DDT with SALV loaded.
6. Type MARK<ESC>G
7. Answer 0 to UNIT #.
8. Answer Y, you are sure.
9. Answer 0<CR> to PACK NO=

Now the disk drive will rattle... if you had one.  SALV doesn't say anything, but it's working.  After two minutes or so, it'll say it's done and start verifying.

**Comment by larsbrinkhoff** [comment]
I *believe* that if "write with header" would just skip the first two words and write the rest to the sector data area, the verification would pass.

There's the separate matter of the actual header data, and the key fields therein, but they are not used to verify the disk pack.

**Comment by rcornwell** [comment]
Try current build. Note you can quickly run it under KI which supports DF10C's. If you plan on running RP04's on KA, I recommend you convert them to similar DF10.

**Comment by larsbrinkhoff** [comment]
Thanks.  From a quick glance reading/writing headers looks good.

I think I have converted everything from 22-bit addressing to 18-bit.  Conditionally, KL still does the former of course.

**Comment by larsbrinkhoff** [comment]
SALV is happy.
