### ISSUE TITLE
KA10: NXM and PAR STOP

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#114]
"Spells and Incantations" has this text:

> To start ITS running, turn off NXM STIO and type $G at exec DDT.  The Salvager should start running; it may take a few minutes to work on the disks.  You may be asked a few yes or no questions concerning memories being turned off, the status of the lineprinter, etc.  Be sure that NXM STOP and PAR STOP are turned ON before the system comes up.

Is turning "NXM STIO", "NXM STOP", and "PAR STOP" on and off supported by the simulator?

**Comment by rcornwell** [comment]
NXM STOP is permanently turned off on the simulator. There is a bit in the PTP punch that comes on if WAITS is configured.

**Comment by larsbrinkhoff** [comment]
Thanks.  "Spells and Incantations" stresses repeatedly that turning on NXM STOP is important for running ITS.  But since everything seems to work fine, I suppose there's no pressing need to investigate more.
