### ISSUE TITLE
KL10: front end functionality

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#115]
I'm curious how you plan to implement the KL10 front end functionality.

I gather you don't intend to run any PDP-11 code.  So that implies implementing features similar to KLDCP and/or RSX20F in the SIMH framework.  Will this be a set of commands in the SIMH command line console?

**Comment by larsbrinkhoff** [comment]
From an ITS point of view, the KLDCP `J` command is used to run scripts in the front end file system.  First, `KLINIT.CMD` is run to poke the KL10 hardware to prepare for running PDP-10 code.  Then, `NTSDDT.CMD` is run to start exec DDT.

Exec DDT is stored in the front end as the file DDT.A10.  "A10" is an "asciized PDP-10 program".  So maybe your front end will have to read this file and convert it to PDP-10 words to store in memory.

**Comment by larsbrinkhoff** [comment]
The contents of `NTSDDT.CMD` is the text "I NTSDD1<CR>".  The `I` command runs a CCL file.  I do not yet have a copy of NTSDD1.CCL.

**Comment by rcornwell** [comment]
Not planing on adding this level of functionally to the simulator. Most of these functions can be done with simH commands now. My goal is to provide the operating system the functions it needs to operate correctly.

**Comment by larsbrinkhoff** [comment]
SIMH commands are fine with me.  I'm just curious what you envision, and how booting ITS will fit in that vision.

As you know, booting ITS on KA10 involves running DSKDMP, traditionally from a paper tape.  But on the KL10 it's not done like that at all.  The gist of it is that exec DDT is loaded from disk.  Will you support that?

**Comment by rcornwell** [comment]
Have not gotten that far. Trying to finish documents and get KA released. Then will get Tops 10 and 20 running on KL, then try ITS.

**Comment by larsbrinkhoff** [comment]
Tangentially, KLH has written:

> DEC diagnostics [...] must be taken with large grains of salt.  Many stopped working for the latest KL10s, and some only worked when loaded with older microcode

**Comment by larsbrinkhoff** [comment]
\<kiteguy> Ok... I will probably add ablity for FE to load files from FE filesystem

Sounds good.  The boot disk sector 1 (and a copy in sector 10) is the HOME block.  It has information where the FE directory is.  The directory lists all file names and the physical sector number and the number of sectors.  All FE files are contiguous on disk.

PDP-10 binaries in the FE filesystem had suffix A10 and are "asciized".

The real way to load DDT is to run the FE script "NTSDDT.CMD", which in turn calls a CCL script, which I suppose must load "DDT.A10".  I'm guessing you'll just do the last step.
