### ISSUE TITLE
KA10: Add DC76 terminal multiplexer for ITS multi-user access.

### ISSUE THREAD

**Issue by rcornwell** [rcornwell/sims#13]

**Comment by larsbrinkhoff** [comment]
See this message from @philbudne about the DL10:  
http://www.classiccmp.org/pipermail/cctalk/2018-January/037545.html

**Comment by philbudne** [comment]
For completeness:  It seems unlikely that ITS ran DEC front-end software (I think IOELEV is what JNC said was likely).

Even in the 1980's I think most people would have been using ITS over TCP, using SUPDUP, or at least TELNET so talking TCP over  a simulated IMP interface (as KLH10 does) would seem a better priority!

**Comment by rcornwell** [comment]
This is no longer needed since Lars added the Morton and TK10 devices.

**Comment by larsbrinkhoff** [comment]
The Morton box, TK10 (Knight kludge), and DK10 (Datapoint kludge) are specific to the KA10 ITS machines.

What do we have for TOPS-10, TENEX, and WAITS?

**Comment by philbudne** [comment]
Looking at 134-tenex TTYSRV.MAC.217

I see:

    IFN NDLS,<

    ;DC10E CORRESPONDENCE TABLES
    ;CORRESPONDENCE IS GIVEN BY PARAMETERS OF THE FORM DC10GX=Y
    ;WHICH MEANS THAT LINE GROUP X IS CONTROLLED BY DC10E GROUP Y

And it looks like the DC10 Data Line Scanner is already present in
sims/PDP10, which TOPS-10 should also be happy with.  For KA10 era
systems I'd imagine the PDP-8 based 680 on a CCI interface was cheaper
and more common.

Rich Alderson may know what KL era WAITS expects, I remember him
telling me one problem he had to deal with bringing WAITS up on a
vanilla KL was how much custom hardware the system expected to find!

DC10 support is present in 3.19, tho modern Un*x seems to have come to
think time_t is unsigned, and the the files are dated 2104!
Repent 2034 is near!  BUILDT.MAC contains:

TITLE   BUILDT - DEFINE AND LOAD A T-S MONITOR FOR PDP-6 OR PDP-10
SUBTTL  W. O'NEILL/RAP  TS3.19  24 SEP 68  V006
.......
        SIXBIT  /WHICH OF THE FOLLOWING LINE SCANNERS DO YOU HAVE?#/
        PUSHJ   P,TCRLF
        JSP     A,BTYPE
        SIXBIT  /DCS (DATA COMMUNICATION SYSTEM 630)#/
        PUSHJ   P,TCRLF
        JSP     A,BTYPE
        SIXBIT  /DLS (DATA LINE SCANNER DC10)#/
        PUSHJ   P,TCRLF
        JSP     A,BTYPE
        SIXBIT  /CCI (COMPUTER-COMPUTER INTERFACE DA10 WITH PDP-8 AND 680 SYSTEM)#/

**Comment by larsbrinkhoff** [comment]
I think MIT's MC was delivered with a DC76.  As per comments in ITS source code.

But true to their habits, ITS hackers modified the software and hardware beyond recognition.  The PDP-11 software is IOELEV as Phil wrote above.  T300 disks were added.

**Comment by larsbrinkhoff** [comment]
To elaborate, from comments in ITS it looks like MIT-MC was delivered with the DC76 option.  It is a PDP-11 with terminal lines interfaced through DL10.  It looks like the MIT hackers went to town and modified it almost beoynd recognition.  The DL10 version of IOELEV also have T300 disks and two Chaosnet interfaces.

@eswenson1 and I are interested in adding DL10 and speak the IOELEV protocol.  This can be considered a long term project.  Maybe this issue can remain closed, and when we have something to show we can open a new one.

(An ever longer term project would be to have DL10 talk to an external PDP-11 emulator running the IOELEV code.)
