### ISSUE TITLE
KI10: Galaxy SPRINT Card images

### ISSUE THREAD

**Issue by pascalgp** [rcornwell/sims#130]
Running Galaxy Release 2 on 6.03 with VMSER (required), all non-space characters from the card reader are interpreted by SPRINT as backslashes.

```
!si-msglvl 003
!20:30:50(SI)
        /
!start
!20:30:53(SI)
        \\\\ \\\\\\ \\\\\                                                       
```

The job card is:

`$JOB QUADRA [1,2]`

Error from Job output:

```
20:30:52 STERR  ?SPTIJC Illegal JOB Card
        Card= \\\\ \\\\\\ \\\\\
```

The same card input is interpreted correctly by CDRSTK.

**Comment by rcornwell** [comment]
Can you email me a log of how you set up Galaxy and some instructions on using it. Unless it is the same as the standard opser command.

**Comment by pascalgp** [comment]
I emailed you instructions.

**Comment by pascalgp** [comment]
Fixed
