### ISSUE TITLE
NOVA software

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#133]
NOVA; NVMIDS 24 - Nova Midas (assembler).  
NOVA; DISPLA 51 - Nova display (for Logo?).  
NOVA; NOVCON .008 - Nova console.  
RADIA; DEBUG 6 - debugger.  
RADIA; EIGHT 109  
RWW; NDTEST 36  
NOVA; .LODEE 0.11

**Comment by rcornwell** [comment]
What does this have to do with any of my simulators?

**Comment by larsbrinkhoff** [comment]
Sorry, wrong repository!
