### ISSUE TITLE
KA10: Old ITS needs CONI MTC bit 0 set

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#134]
ITS 724 and 785 needs CONI MTC to have bit 0 set to indicate it's assigned to the PDP-10.  Apparently the TM10 was shared with the PDP-6 like the 340 etc.

**Comment by rcornwell** [comment]
Should be easy to add to only show up when ITS is selected.

**Comment by rcornwell** [comment]
Added setting of bit 0 when running under ITS mode.

**Comment by larsbrinkhoff** [comment]
Thanks!

**Comment by larsbrinkhoff** [comment]
Confirmed fix working.
