### ISSUE TITLE
KA10: LPT Attached file rewind

### ISSUE THREAD

**Issue by pascalgp** [rcornwell/sims#137]
With each job sent to the LPT device, the emulator automatically starts writing at the beginning of the attached file, overwriting what was already there (if anything).

**Comment by rcornwell** [comment]
I have seen this... I think I need to track position in the device output.

**Comment by rcornwell** [comment]
This should be fixed in the current commit.

**Comment by pascalgp** [comment]
This is resolved. Thank you.
