### ISSUE TITLE
KA10: LPT/LP10 Control codes

### ISSUE THREAD

**Issue by pascalgp** [rcornwell/sims#138]
There are issues with the interpretation of control codes sent to the printer. For instance, the PDP10-Kx emulators interpret DC3 as a 10 line vertical tab which would appear to be incorrect.

Please refer to: "DEC-10-XSRMA-A-D DECsystem10 System Reference Manual.pdf" pages 4-2/4-3

On an LP10 set up with the standard format tape, a DC3 (octal 023) produces a single line space (line feed) just like an LF (octal 012) except that LF will cause a Form Feed after printing 60 lines on a given page whereas DC3 will not. The printer spooler (LPTSPL) makes use of DC3s for separator pages so it can print across all 66 lines of a physical page. This is also convenient for some reports as well as ASCII art printouts where a 6 line break between pages is not wanted. Looking at ka10_lp.c, DLE (020), DC1 (022), DC2 (023) would also be interpreted incorrectly per DEC's documentation. As it stands, the separator/header pages of a batch job which would normally fit on 2 fanfold form pages will actually result in 18 pages of printout.

**Comment by rcornwell** [comment]
So DC3 should be single line, but not generate a FF it it passes lines/page. 
What should the other DC codes produce?

**Comment by pascalgp** [comment]
According to the System Reference Manual, the standard format tape defines a "logical" page length of 60 lines. It seems that the page length could be changed by using a different format tape although I can't find specifications for that. In any case, the hard limit on a standard fanfold page at 6 lines/inch is 66 lines per page. It doesn't look like the LP10 could print at 8 lines/inch like the IBM 1403.

Knowing that, I would set the emulator page length at 60 lines. Software can then print beyond the 60th line with DC3s.

From the documentation (lines being numbered 0 to 59):

- FF (014) Top of form. Position to line 0

- CR (015) Strict carriage return (no spacing)

- LF  (012) Line feed: Positions to next line (0 through 59) with auto FF after 60 impressions

- DC1 (021) Double space: Positions the printer to the next even numbered line (0 through 58) with auto FF after 30 impressions

- DC2 (022) Triple space: Positions to next third line (0 through 57) with auto FF after 20 impressions

- DC3 (023) Single space: Every line without auto FF

- DC4 (024) Space one sixth of a page (position to line 0, 10, 20, 30, 40, 50)

- VT (013) Vertical Tab, space one third of a page (position to line 0, 20, 40)

- DLE (020) Space half a page (position to line 0, 30)

**Comment by rcornwell** [comment]
For other Line Printer devices I have an option to set the page size. Once the page size is it, a form feed is generated. I can add that functionally to the LP10. I will fix the control characters to match this list. Expect a patch for both error tomorrow.

**Comment by rcornwell** [comment]
Let me know if this is correct now.

**Comment by pascalgp** [comment]
DC3 no longer generates form feeds which is the correct behavior. However, DC3 now does a double space when it should really do a single space (no different from LF). For instance, this command:

```
.COPY LPT:=TTY:
A
B
C
1^S2^S3
^Z

.
```

will result in this print output:

```
A
B
C
1

2

3
^Z
```

(Note that ^S is a DC3.) There shouldn't be an empty line between 1 and 2 as well as 2 and 3. DC3 should behave like the LF between A and B and C.

**Comment by rcornwell** [comment]
Try the current version.

**Comment by pascalgp** [comment]
Resolved. Thank you.
