### ISSUE TITLE
IBM360: Getting TSO to run on OS/360

### ISSUE THREAD

**Issue by rcornwell** [rcornwell/sims#139]
Unable to get TSO to run on OS/360. It gets address exception on first connect attempt due to accessing invalid location to get terminal number.

**Comment by rcornwell** [comment]
Fixed in current version.

**Comment by wrljet** [comment]
Are there any DASD images and/or instructions on how to run the various OSes on the 360 simulator?

**Comment by rcornwell** [comment]
Yes, there is an OS/360 build setup in sky-visions.com/IBM360/os360.zip. I also put up a VM/370 gen in there. IBM360 is compatible with uncompressed DASD volumes from Hercules. Note devices in IBM360 are not arbitrary. Channels 0 and 4 are multiplexer, all others are selector.

For OS360, you want "ibm360 os2311a.ini" to start the install. For VM/370 it is "ibm360 vm.ini" and ibm360 vm_r.ini to run.

**Comment by wrljet** [comment]
Excellent!  Thank you.

Bill
