### ISSUE TITLE
KA10: LPT 132 Character lines

### ISSUE THREAD

**Issue by pascalgp** [rcornwell/sims#140]
After writing a line with exactly 132 characters, the emulated LP incorrectly writes an empty line.

As a result, sending a text file with exactly 132 characters per line to the printer (either directly or through the spooler) generates a double spaced printout.

**Comment by rcornwell** [comment]
LPT should flush the line after reaching col 132. If a carriage return character follows this will result in a blank line. From reading the documents since would be the behavior on a real printer. After receiving 132 characters the printer will dump it's buffer and continue on.

**Comment by pascalgp** [comment]
Does flushing the buffer actually imply sending a command to print it?

From the LP10 description in [DEC-10-XSRMA-A-D DECsystem10 System Reference Manual.pdf] page 4-2:

"The printer has a 132-character buffer that holds the image of a single line; the program must first load the buffer up to five character at a time, **and then give a control character** to print the entire line."

This seems to indicate that at the hardware level, the printer will accept up to 132 chars but not print them until it receives a control char.

No the same printer, but maybe worth mentioning that the LP20 as emulated in SIMH won't write an empty line after writing a 132 character line when copying a file directly to the LPT: device under 7.03.

**Comment by rcornwell** [comment]
1970PDP10Ref_Part1.pdf,  page 4-5, 

> If the buffer is filled with 132 characters and the next character does not cause printing, the interface simulates a line feed to print and advance the paper, and then load the next character at column 1 for a new line.

The LP10 and the LP20 printer are somewhat different.

**Comment by pascalgp** [comment]
Agreed. But the document I was citing describes the LP10, not the LP20.

**Comment by rcornwell** [comment]
DEC-10-BHAD-D_BA10_Hard_Copy_Controller_Maintenance_Manual_Sep72.pdf Page 6-18.

> Transferring 132 consecutive printing characters to the printer fills the memory to capacity. If character 133 initiates a printing operation, the memory is emptied and the printer is ready to receive additional printing characters; however, if character 133 is a printing character, the control logic must force a printing operation. The operation is such that printing character 133 is not lost; instead, character 133 becomes the first character sent to the line printer for the next print cycle and appears at the left margin of the next line.

**Comment by pascalgp** [comment]
What makes this confusing is that "printing character" really means a "printable character" which excludes control codes.

That is made a little more clear here, in the same document: "DEC-10-BHAD-D_BA10_Hard_Copy_Controller_Maintenance_Manual_Sep72.pdf" Page 6-19, 6.7.9.1:

"The LDPA PRINTING CHAR level is always generated by the codes 040{8} through 176{8} (printing characters) and..."

So, we send 132 printing (i.e. printable) characters to the printer and the buffer is now full but nothing happens quite yet. We then send character 133, a CR (015) which initiates a printing operation but is not a printing character. The line is printed naturally (as it would if it were shorter) and the buffer is emptied. Only when character 133 is a printing (printable) character does the printer logic force printing so that no printable characters are lost - which is not the case for the 132 char line followed by CR-LF (or CR-DC3) that we're talking about.

**Comment by rcornwell** [comment]
Ok... will see if I can duplicate this logic.

**Comment by pascalgp** [comment]
Fixed
