### ISSUE TITLE
KA10: Boot from 7-track magtape

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#143]
Doesn't seem to work?

I see this in mt_boot:

```
    uptr->CNTRL = 022200; /* Read 800 BPI, Core */

**Comment by rcornwell** [comment]
This is to give the controller some default value.

mt_boot will read in a wc,addr followed by data followed by a JSRT begin. Basically it simulates readin mode on real CPU.

**Comment by larsbrinkhoff** [comment]
Note, *7-track* tape images.

Booting works with suitable changes to mt_read_word.

**Comment by rcornwell** [comment]
Not sure I ever tried real 7 track images. :-)

**Comment by rcornwell** [comment]
Can you attach the tape image here and I can try a patch I did.

**Comment by larsbrinkhoff** [comment]
Here it is.

```
set mta 7t
at mta0 magdmp.tape
b mta0
```

[magdmp.zip](https://github.com/rcornwell/sims/files/3489505/magdmp.zip)

Should output `MAGDMP` when it starts, and accept and echo characters.

**Comment by larsbrinkhoff** [comment]
I used this to test booting.  Of course, the real thing should work with both 9 and 7 track tapes.

```
void mt_read_word(UNIT *uptr) {
     int i, cc, ch;

     mt_df10.buf = 0;
     for(i = 0; i <= 5; i++) {
        cc = (6 * (5 - i)) + 0;
        ch = mt_buffer[uptr->BPOS];
        if (cc < 0)
            mt_df10.buf |=  (uint64)(ch & 0x3f);
        else
            mt_df10.buf |= (uint64)(ch & 0x3f) << cc;
        uptr->BPOS++;
     }
}

**Comment by rcornwell** [comment]
This tape does not appear to be correct.

sim> set mta0 7t
sim> at mta0 magdmp.tape 
sim> bo mta0
Boot: 777761000000
Boot: 002550000000
Boot: 000054144000
Boot: 000004734700
Boot: 400000012500
Boot: 400000000300
Boot: 241011777700
Boot: 767340710000
Boot: 001025601100
Boot: 000010256000
Boot: 110000133600
Boot: 444000000000
Boot: 312000000000
Boot: 172700170000
Boot: 000033174000
Boot: 000000254200

It looks like you have the wrong number of characters per word. For 7 track tape it should be 6 frames per word. Also each frame should be in ODD parity. A 000 frame on a real tape could not be read!

**Comment by larsbrinkhoff** [comment]
I'll fix the parity.

My image looks like this:

```
0000000 144 016 000 000 077 077 161 000 000 000 125 050 000 000 000 000
0000020 154 014 140 000 000 104 173 047 140 000 000 101 125 140 000 000
0000040 000 003 024 110 011 077 077 176 173 140 071 000 000 110 125 060
...
```

- `144 016 000 000` is the record length.
- `077 077 161 000 000 000` are six frames that encode `777761000000`
- `125 050 000 000 000 000` is `255000000000`
- `154 014 140 000 000 104` is `541440000004`
- etc

Did I send you the wrong file?

**Comment by rcornwell** [comment]
Got it... pushed commit out.

**Comment by larsbrinkhoff** [comment]
Works.
