### ISSUE TITLE
KI10: Tops-10 6.03 VMSER - Paging errors

### ISSUE THREAD

**Issue by pascalgp** [rcornwell/sims#147]
With Galaxy 2 Quasar running in OPSER, trying to list a queue causes paging errors:

```
.queue lpt:/list
?
?Monitor error at user PC 401004
```

Errors on the console:

```
!
?CPU0 monitor error. stopcode name NFS
Continuing system

?CPU0 monitor error. stopcode name IPM
JOB 8 ON TTY0 RUNNING QUEUE
UUO is 47100000142 at user PC 401005
?Aborting job
```

Also, the FINE (Emacs like) editor allows editing files up to about 450 blocks in size on 6.03/KA and up to 900 blocks on KI. On KI with VMSER, trying to read a file larger than 20 blocks gives this error:

```
Read File: t100.mac$?
?Can not get PFH?
?Ill mem ref at user PC 416555
```

**Comment by rcornwell** [comment]
> MCO D-7808      TW
----------

ONCMOD          K4SOK

SYMPTOM:        STOPCD IPM.

DIAGNOSIS:      1ST BLOCK FOR SWAPPING MUST BE A MULTIPLE OF 4.  ONCMOD DOES
                NOT ENFORCE THIS.

CURE:           TRZ AC,3.

Can you email me a tape of FINE and build steps?

**Comment by rcornwell** [comment]
This is probably a typo in VMSER.MAC

**Comment by rcornwell** [comment]
With the new VMSER tape from Al latest drop, and a simple patch to load_tbl, this bug is finally gone.

One issue is on KI the opser does not start automatically.
