### ISSUE TITLE
KA10: IMP support

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#16]
![](http://i.dailymail.co.uk/i/pix/2014/03/06/article-0-1C16DE7600000578-182_634x372.jpg)

**Comment by larsbrinkhoff** [comment]
There were two kinds of IMP interfaces: KAIMP used with AI, ML, and MC, and DMIMP.

**Comment by larsbrinkhoff** [comment]
Setting KAIMP==1 builds ITS with the IMPOLD WTHNCP.  I enabled TCP/IP, but not NCP.

Booting this crashes.  But if I also set C1MXP it runs, which is encouraging.

**Comment by larsbrinkhoff** [comment]
I made some ugly hacks to the simulator, but TM10A now works with C1MXP.

Basically just rerouting the channel 1 interrupt loation from 42 to 76.  Now to get it working with multiple devices...

**Comment by rcornwell** [comment]
If you want to send me the patches I can try and clean them up and integrate them. The low level IRQ system is rather convoluted.

**Comment by larsbrinkhoff** [comment]
Yes, I will certainly send them over when I think they're ready.  Not just yet...

**Comment by larsbrinkhoff** [comment]
This is the current state.  Just to make TM10A work with c1mpx.  The tape device can now say it wants interrupts to go to location 76.  It should be configurable.

https://github.com/rcornwell/sims/compare/master...larsbrinkhoff:c1mpx

It this in the right direction, or am I barking up the wrong tree?

**Comment by rcornwell** [comment]
You are barking up the wrong tree here. Also this will break other systems! 
Try explaining what you need this to do and I can see about implementing it cleanly.

**Comment by larsbrinkhoff** [comment]
This is still somewhat experimental.

I need devices (magtape, dectape, and IMP) interrupting at channel 1 to go to locations in a range 66-76 instead of 42.

See C1MXP conditional in ITS.

**Comment by larsbrinkhoff** [comment]
I'm thinking this could be enabled by something like

    set mta vector 76

**Comment by rcornwell** [comment]
Wrong approach. From what I understand the MPX was a device that re-vectored interrupts for a given device. The PI channels that devices were on was controlled by software. My initial thought it to add a flag to the devices that could be on the MPX device as a flag. 

  set mta mpx

Then have the MPX device be a psuedo device that re-vectored interrupts of devices on it. 

What did the PI settings of the device control?

**Comment by larsbrinkhoff** [comment]
My only understanding is from the ITS source code.  Enabling C1MXP makes PI channel 1 interrupts go here instead of 42:

- IMX → 66 (we can probably ignore this for now)
- IMP input → 70
- IMP output → 72
- DECtape → 74
- Magtape → 76

I'm fine with anything that can accomplish this.

**Comment by larsbrinkhoff** [comment]
> From what I understand the MPX was a device that re-vectored interrupts for a given device.

As you can see, several devices are re-vectored.  And only PI channel one is affected.

> What did the PI settings of the device control?

Do you mean the bits set by CONO?  The PI level is still the same as before.  I expect that if, say, magtape data was made to interrupt at some other channel than 1, it would not be affected by multiplexing.

**Comment by rcornwell** [comment]
I thought that this device had some cono/coni bits to select whether the device was attached to the PDP6 or PDP10? 

I will have to look at the source and see what they are doing.

**Comment by larsbrinkhoff** [comment]
There is such a multiplexing device, but it's a separate thing.  It's not related to channel 1 multiplexing.

There are just a few C1MXP in ITS.  Looking at those places should clear it up.

**Comment by b4** [comment]
I vote for whichever can also be applied to TENEX ;)

**Comment by larsbrinkhoff** [comment]
@b4, bring out the documentation!  Or source files.

Chances are, TENEX uses something else.  There's also the possibility that in the future there could be a Unibus IMP interface for use with the KS10 in SIMH.

**Comment by larsbrinkhoff** [comment]
I will try to separate the Host/IMP interface from the IMP itself.  To make it easier to add more interfaces, like the Metcalfe DM thing, Unibus, TENEX, whatever.

This might even be useful outside PDP-10.

**Comment by larsbrinkhoff** [comment]
I hope it's ok for me to make some random notes here.

List of IMP interfaces:

- KA IMP: PDP-10 I/O bus.
- DM IMP: PDP-10 I/O bus.
- ACC LH/DH: Unibus.
- DEC IMP11-A.

**Comment by larsbrinkhoff** [comment]
Did some more work yesterday.  ITS is now trying to send packets, first a NOP to see if the IMP is up.  There are interrupts raised and handled.  Most of hw memo # 10 is implemented.

BLKO seems to write two words in quick succession.  Too quick, so the first is lost.  Will check on that later.

**Comment by larsbrinkhoff** [comment]
@rcornwell Channel 1 multiplexing is a little more interesting than I thought.  The IMP interface can interrupt to locations 42, 70, or 72!  It depends on the interrupt condition inside the device.  HW memo 10 spells this out.

**Comment by larsbrinkhoff** [comment]
Looking for advice.  Do you think the IMP device should receive data asynchronously with callbacks, or should it pull for data in the srv routine?  Which is a better fit for the SIMH design?

**Comment by larsbrinkhoff** [comment]
It now works to the extent that I can telnet from my Linux host to KA ITS.

I'll start cleaning up for merging.  I'll implement your PI channels 8-15 idea.

**Comment by larsbrinkhoff** [comment]
I removed the set_interrupt_mpx function and made the set_interrupt function accept levels 0-17, where 10-17 are the pseudochannels (the ITS names for those).

For this to work, I had to change many device simulators to mask the set_interrupt argument with 7.  Maybe you'd rather have them store the interrupt assignment separately and pass that directly.  Your call.

I did not, for now, change which bits are set in dev_irq[] or how pi_enc is computed.  I think maybe you want to figure that out.  I also haven't made this user configurable.

Anyway, in this half-finished state it seems to work quite solidly with ITS.  I tested reading and writing with TM10A.

This is all contained in a single commit in my ka10-simh fork, in the c1mpx branch.

**Comment by rcornwell** [comment]
I have made some changes to the irq handling and the tm10 driver let me get the machine passing diagnostics and I will add in the MPX device. Changing set_interrupt mask will break way to many things. I think this will be up to the device to call the correct set_interrupt function, since the MPX device will be implemented as a second PI controller. After I get the changes checked in I will add mpx to the TM10 and test that.

**Comment by larsbrinkhoff** [comment]
The KA IMP seems to work fine with the latest simulator, once you patch ITS like this:  
https://github.com/PDP-10/its/commit/21d263bd5f83a3ee6c08b21da08a7fb16497af8f

You don't need to reassemble ITS; you can do a binary patch in exec DDT.

Boot to DSKDMP  
its  
IPGOQ6-2/ JFCL ^J  
JFCL ^M  
$U  
D$ working its

**Comment by larsbrinkhoff** [comment]
The ITS repo branch lars/kaimp has the necessary (source) patch and now completes a full build.

**Comment by rcornwell** [comment]
To configure imp:
set imp enable
set imp mac=9a:72:60:f7:8c:20
set imp ip=192.168.0.20/24
set imp gw=192.168.0.1
set imp host=10.3.0.6
set imp mpx=4

at imp tap:tap0

 If host=0.0.0.0 or not set there is no NATing

**Comment by rcornwell** [comment]
Still to do:
   -  Add DHCP support. 
   - Better IMP emulation
   - Timeout support for ARP timeout.

**Comment by rcornwell** [comment]
Script I used to set up tap interface. Ubuntu 16.04

#!/bin/sh
HOSTIP=`/sbin/ifconfig enp3s0 | gawk -- '/inet/{ print substr($2,6) }'`
HOSTNM=`/sbin/ifconfig enp3s0 | gawk -- '/inet/{ print substr($4,6) }'`
HOSTBR=`/sbin/ifconfig enp3s0 | gawk -- '/inet/{ print substr($3,7) }'`
HOSTGW=`/sbin/route -n | gawk -- '/^0.0.0.0/{ print $2 }' | head -n 1`

#
echo "Host Addr ${HOSTIP}"
echo "Netmask ${HOSTNM}"
echo "Broadcast ${HOSTBR}"
echo "Default GW ${HOSTGW}"
#
/usr/sbin/tunctl -t tap0 -u rich
/sbin/ifconfig tap0 up

#
# Now convert eth0 to a bridge and bridge it with the TAP interface
/sbin/brctl addbr br0
/sbin/brctl addif br0 enp3s0
/sbin/brctl setfd br0 0
/sbin/ifconfig enp3s0 0.0.0.0
/sbin/ifconfig br0 $HOSTIP netmask $HOSTNM broadcast $HOSTBR up
# set the default route to the br0 interface
/sbin/route add -net 0.0.0.0/0 gw $HOSTGW
# bridge in the tap device
/sbin/brctl addif br0 tap0
/sbin/ifconfig tap0 0.0.0.0
echo "nameserver $HOSTGW" >>/etc/resolv.conf

**Comment by larsbrinkhoff** [comment]
I made a little progress testing this.  Built ITS from scratch with the latest master here; seems fine.  Rebuilt ITS with IMP and TCP/IP enabled.  Added the `set imp` commands.  Then I saw the tap script.  That's quite a mouthful!

KLH10 makes this much easier.  What's the difference?  Doesn't sim_ether offer any help?

**Comment by rcornwell** [comment]
Not sure what kind of "help" you are looking for?

**Comment by larsbrinkhoff** [comment]
With the KLH10 IMP, I just tell it what IP address it has, and what gateway to use.  That's the kind of help I'd appreciate.

**Comment by rcornwell** [comment]
set imp gw=ip    sets gateway address
set imp ip=ip/mask bits   sets address which ITS will appear at.

set imp host=ip    Sets address of ITS if different from ip/mask address.

The tap script about just creates a tap interface. This is the same as all simh simulators.

**Comment by rcornwell** [comment]
DHCP support now working. NATing is mostly working. There is some performance issues I need to resolved before this code is considered done. Tested with FTP and TELNET.

**Comment by larsbrinkhoff** [comment]
I'm trying to test this, but I'm running into a problem:

    can't add wlan0 to bridge br0: Operation not supported

According to information online, you can't bridge a WLAN interface.

**Comment by rcornwell** [comment]
By WLAN do you mean wi-fi or WAN (ie mobile setup?)

Note this is a OS issue not a IMP issue.

Also you will need to make sure your network supports IPV4.

**Comment by larsbrinkhoff** [comment]
This XQ document says to use SLiRP -- "nat:" -- for WiFi.  
https://github.com/simh/simh/blob/master/0readme_ethernet.txt

**Comment by rcornwell** [comment]
Try dropping the slirp and slirp_glue directories into your sims repo and recompiling KA10. This should work, you will probably need to change the IP address of ITS to work with Slirp address. I am not sure if FTP will work fully. Directory list and file transfer require changes to the data stream. You should be able to enable DHCP and just give it the same address as slirp.

**Comment by larsbrinkhoff** [comment]
Where do I find these directories?  I searched for "slirp_glue" without obvious success.

**Comment by rcornwell** [comment]
From simh master tree.

**Comment by larsbrinkhoff** [comment]
I added the slirp directories, installed libpcap-dev, bridge-utils, and uml-utilities.  Yet all I get is:

```
sim> show eth
ETH devices:
  network support not available in simulator

**Comment by larsbrinkhoff** [comment]
As far as I can see, the toplevel makefile doesn't set `NETWORK_USEFUL = true` for the ka10 target.  When I added this, I do get a list of Ethernet interfaces:

```
sim> show eth
ETH devices:
 eth0   tap:tapN                             (Integrated Tun/Tap support)
 eth1   nat:{optional-nat-parameters}        (Integrated NAT (SLiRP) support)
 eth2   udp:sourceport:remotehost:remoteport (Integrated UDP bridge support)
libpcap version 1.7.4

**Comment by larsbrinkhoff** [comment]
When attaching to nat: I get this.

```
/home/lars/src/its4/build/sims/run-24> at imp nat:
libpcap version 1.7.4
NAT args: 
NAT network setup:
        gateway       =10.0.2.2/24(255.255.255.0)
        DNS           =10.0.2.3
        dhcp_start    =10.0.2.15
```

I'm not sure how to proceed from here.

**Comment by larsbrinkhoff** [comment]
You wrote:

> Not sure how to proceed with NAT, I have not used that solution... just use TAP

I think we established that TAP doesn't work with WiFi?

**Comment by rcornwell** [comment]
You should just have to set the HOSTIP to the ITS host IP, and enable DHCP. It should auto configure. However NAT requires some parameters to connect ports. See the README file for that.

**Comment by larsbrinkhoff** [comment]
So like this?

```
set imp enabled
set imp dhcp
set imp host=10.3.0.6
```

No ethernet bridge needed?

Is DCHPIP needed, or will it do a broadcast?

**Comment by rcornwell** [comment]
DHCPIP should be  set automatically by the server. It is the IP address of the DHCP server. It broadcasts and grabs a lease, and renews it as needed.

**Comment by larsbrinkhoff** [comment]
Will this work without an Ethernet bridge?

I'm looking for a way to test this with WiFi only.

**Comment by rcornwell** [comment]
This will appear as ports on your machine. So for example:

at imp nat:tcp=2323:10.0.2.15:23

Telneting to port 2323 on your host will telnet into ITS.

Note you might want to define ITS to have an IP address of 10.0.2.15 so that there is no nat involved. If this is the case, set hostid=0 (or don't define it).

To properly run the machine over wifi link requires a bit of software on the linux box, but not sure what.

**Comment by larsbrinkhoff** [comment]
https://askubuntu.com/questions/885260/mapping-tap-interface-with-wifi-interface

**Comment by rcornwell** [comment]
https://wiki.debian.org/BridgeNetworkConnections

**Comment by larsbrinkhoff** [comment]
ebtables

**Comment by rcornwell** [comment]
This appears to be working.

**Comment by larsbrinkhoff** [comment]
I'm experimenting with bridging now.  I managed to fumble away network access to my remote server, but I got it back.  Phew.

**Comment by larsbrinkhoff** [comment]
I get no ping replies.  What am I missing?  I have this:

```
set imp enabled
set imp mac=9a:72:60:f7:8c:20
set imp ip=192.168.2.101/24
set imp gw=172.31.1.1
set imp host=10.3.0.6
at imp tap:tap0
```

Looks ok:

```
sim> show imp
IMP     MAC=9A:72:60:F7:8C:20, MPX=4, IP=192.168.2.101/24
        GW=172.31.1.1, HOST=10.3.0.6, DHCPIP=0.0.0.0
        attached to tap:tap0, DHCP disabled, MIT
```

The bridge is active:

```
$brctl show
bridge name     bridge id               STP enabled     interfaces
br0             8000.5254a201d8f0       no              eth0
                                                        tap0
```

The interfaces:

```
$ifconfig br0
br0       Link encap:Ethernet  HWaddr 52:54:a2:01:d8:f0
          inet addr:172.31.1.100  Bcast:172.31.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
```

```
$ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 52:54:a2:01:d8:f0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
```

```
$ifconfig tap0
tap0      Link encap:Ethernet  HWaddr e2:6c:84:1d:34:a3
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
```

**Comment by rcornwell** [comment]
Why do you have your ITS IP address at 192.168.x.x when your on a 172.31 network?

You might try enabling DHCP and allowing your local provider to give you an IP address. Once it is set you can view it with show imp.

**Comment by larsbrinkhoff** [comment]
My VPS has the IP number 172.31.1.100 (but 88.99.191.74 externally).  I can't get another IP number from DHCP.

I have KLH10 using IP number 192.168.1.100.  I'm trying to get ka10 to use 196.168.2.101.

**Comment by larsbrinkhoff** [comment]
Routing table:

```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         172.31.1.1      0.0.0.0         UG    0      0        0 br0
172.31.1.0      *               255.255.255.0   U     0      0        0 br0
192.168.1.100   *               255.255.255.255 UH    0      0        0 tun0
192.168.2.101   *               255.255.255.255 UH    0      0        0 br0

**Comment by larsbrinkhoff** [comment]
IMP DEBUG shows this when pinging:

```
DBG(589269120)+> IMP DATAIO: received  dst: FF:FF:FF:FF:FF:FF  src: 52:54:A2:01:D8:F0  proto: 0x0806  len: 42  crc: 45195C2D
DBG(589269120)+> IMP DATAIO: rcvqd  dst: FF:FF:FF:FF:FF:FF  src: 52:54:A2:01:D8:F0  proto: 0x0806  len: 60  crc: D4D9D9F8

**Comment by larsbrinkhoff** [comment]
Two changes:
- Made imp mac same as tap0 mac address.
- Made imp gw the host computer IP number.

Now I get a telnet connection to ITS.
