### ISSUE TITLE
KA10: Chaosnet support

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#17]

**Comment by larsbrinkhoff** [comment]
There were two flavours of Chaosnet interfaces used with the KA10 machines:

- T11CP: goes through a dedicated PDP-11 attached to the MIT-AI 10-11 interface.
- CH10P: attached to I/O bus.
- In addition, DLCP went through DL10 on the KL10.

**Comment by larsbrinkhoff** [comment]
I think CH10 might be the easiest device to simulate.

**Comment by larsbrinkhoff** [comment]
Some documentation:  
https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/pdp10.caios

**Comment by larsbrinkhoff** [comment]
From SYSTEM; CHAOS 289.  Apparently the first word read from a packet is garbage.

```
        DATAI CHX,T             ;FIRST DATAI YIELDS GARBAGE
```

**Comment by larsbrinkhoff** [comment]
I have a quick-and-dirty CH10 on a branch.

**Comment by rcornwell** [comment]
Added to latest release.

**Comment by rcornwell** [comment]
This appears to be working. We can reopen it if there is any issues with it.
