### ISSUE TITLE
KA10: Interface with PiDP-10

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#172]
Is there a plan for this?

CC @PiDP

**Comment by rcornwell** [comment]
Have not heard anything on this in a while.

**Comment by larsbrinkhoff** [comment]
Here's a prototype of the PiDP-10 firmware:  
https://github.com/larsbrinkhoff/pidp10-firmware

**Comment by larsbrinkhoff** [comment]
Pull request #292 was a small step towards adding in PiDP-10 features.

**Comment by rcornwell** [comment]
I will wait until I can test this. Can you add documentation here to describe where the switches and lights are located in terms of i/o pins and mux status?

**Comment by larsbrinkhoff** [comment]
There's no clear information on how the IO works, but it should be possible to figure out from the firmware sources.

**Comment by rcornwell** [comment]
Oscar sent me a copy of the schematic. I have a pin map now.

**Comment by larsbrinkhoff** [comment]
This is done.
