### ISSUE TITLE
I7000: Type inconsistency for global array assembly

### ISSUE THREAD

**Issue by markpizz** [rcornwell/sims#174]
```
  simh\I7000\i7000_defs.h(272):extern t_value  assembly[NUM_CHAN];             /* Assembly register */
  simh\I7000\i7010_chan.c(67):uint32              assembly[NUM_CHAN];         /* Assembly register */
  simh\I7000\i701_chan.c(53):t_uint64            assembly[NUM_CHAN];       /* Assembly register */
  simh\I7000\i7070_chan.c(70):t_uint64            assembly[NUM_CHAN];         /* Assembly register */
  simh\I7000\i7080_chan.c(96):uint32              assembly[NUM_CHAN];         /* Assembly register */
  simh\I7000\i7090_chan.c(80):t_uint64            assembly[NUM_CHAN];       /* Assembly register */
```

Should all of these be t_value?

**Comment by rcornwell** [comment]
I am not sure about this. I will have to review the code and see.

**Comment by rcornwell** [comment]
The definition of assembly needs to be moved to i701_def.h and i7090_defs.h , for i701 and i7090, i7070 it should be value_t since it will be 36 bit numbers. For i7080 it should be 32bits. For i7010 it can be uint8.

I can make these changes and push them out if you want.

**Comment by markpizz** [comment]
value_t isn't defined.  t_value is.

Meanwhile, it would seem that the include file definition could stay where it is even though t_value may actually be a different type in different simulators.  The actual storage declaration should be t_value wherever it happens to be defined...

**Comment by rcornwell** [comment]
Here is the patches I came up with. I will need to test the I7010 to make sure it is ok.

`diff --git a/I7000/i7000_defs.h b/I7000/i7000_defs.h
index 78bd285..a5293eb 100644
--- a/I7000/i7000_defs.h
+++ b/I7000/i7000_defs.h
@@ -269,7 +269,6 @@ extern DEBTAB crd_debug[];
 #define UNIT_V_SET      (UNIT_V_UF + 5)
 #define CHAN_SET        (1 << UNIT_V_SET)
 
-extern t_value  assembly[NUM_CHAN];             /* Assembly register */
 /* I/O routine functions */
 /* Channel half of controls */
 /* Channel status */
diff --git a/I7000/i7010_chan.c b/I7000/i7010_chan.c
index 763c854..4b936ad 100644
--- a/I7000/i7010_chan.c
+++ b/I7000/i7010_chan.c
@@ -64,7 +64,7 @@ uint8               cmd[NUM_CHAN];              /* Current command */
 uint16              irqdev[NUM_CHAN];           /* Device to generate interupts
                                                    for channel */
 uint32              chunit[NUM_CHAN];           /* Channel unit */
-uint32              assembly[NUM_CHAN];         /* Assembly register */
+uint8               assembly[NUM_CHAN];         /* Assembly register */^M
 uint32              chan_flags[NUM_CHAN];       /* Unit status */
 extern uint8        chan_io_status[NUM_CHAN];
 extern uint8        inquiry;
diff --git a/I7000/i7090_defs.h b/I7000/i7090_defs.h
index 5681536..a02e13d 100644
--- a/I7000/i7090_defs.h
+++ b/I7000/i7090_defs.h
@@ -29,6 +29,7 @@
 #define ReadP(x)        (M[x])
 #define WriteP(x,y)     if (MEM_ADDR_OK (x)) M[x] = y
 extern t_uint64         M[MAXMEMSIZE];
+extern t_uint64         assembly[NUM_CHAN];^M
 
 /* Processor specific masks */
 #define ONEBIT          00200000000000LL
`

**Comment by markpizz** [comment]
Removing the assembly declaration from i7000_defs.h results in several simulators failing to build.

Making everything t_value (in the 4 definitions) builds cleanly for all simulators.

**Comment by rcornwell** [comment]
Yes it would, however you have to add it into some of the others. Basic change is to remove the definition from i7000_defs.h and add it to i7090_defs.h (as t_uint64) and change i7010_chan.c to uint8.

I will push these changes out in a bit.
