### ISSUE TITLE
kx10_dt can mangle not recognized disk/tape images

### ISSUE THREAD

**Issue by markpizz** [rcornwell/sims#188]
DECtapes were available on a range of DEC systems.  Each could read their own tapes, and sometimes they could exchange tapes with others systems.

A problem which was reported many years ago had to do with the potential mangling of data after an DECtape attach if the image file being attached was not of a recognized type.  The problem is due to the mapping of data expected by one simulator not matching data representation of a tape created by  a different simulator.  This problem existed when moving tapes between 8bit systems , 12bit systems and 18/36 bit systems.  A user might attach a tape image, try to read it on under some OS, but find that it wasn't readable.   The tape detach routine would write out the image of the tape that it expected was correctly aligned when a detach command was executed.   A very defensive user might try to set the drive to write locked before attempting to attach the tape, but not all users are that defensive.  This problem was solved for the pdp11_tc.c, pdp8_dt.c and  pdp18b_dt.c by adding a WRITTEN flag using u5.  This flag was set on any write to the drive and thus the detach could know if the file needed to be written out.  Additionally, there is a io_flush pointer in the UNIT structure.  Disk image files that are buffered in memory like DECtapes and floppies are actively flushed to disk every 30 seconds by SCP.  Look at one of the pdp11, pdp8 or pdp18b for an example.

**Comment by rcornwell** [comment]
Ok, will add this to my dectape devices.
