### ISSUE TITLE
Inconsistent clock API usage

### ISSUE THREAD

**Issue by markpizz** [rcornwell/sims#189]
kx10_cpu as the following real time clock usage:

```
UNIT cpu_unit[] = { { UDATA (&rtc_srv, UNIT_IDLE|UNIT_FIX|UNIT_BINK|UNIT_TWOSEG, 256 * 1024) },
#if ITS
                    { UDATA (&qua_srv, UNIT_IDLE|UNIT_DIS, 0) }
#endif
#if KL
                    { UDATA (&tim_srv, UNIT_IDLE|UNIT_DIS, 0) }
#endif
                   };
```

So there are at most 3 units, 

However:
```

DEVICE cpu_dev = {
    "CPU", &cpu_unit[0], cpu_reg, cpu_mod,
    1, 8, 22, 1, 8, 36,
    &cpu_ex, &cpu_dep, &cpu_reset,
    NULL, NULL, NULL, NULL, DEV_DEBUG, 0, cpu_debug,
    NULL, NULL, &cpu_help, NULL, NULL, &cpu_description
    };
```
Notice that the unit count is 1.  This is wrong, but not causing a direct problem.
```
t_stat
rtc_srv(UNIT * uptr)
{
    int32 t;
    t = sim_rtcn_calb (rtc_tps, TMR_RTC);
    sim_activate_after(uptr, 1000000/rtc_tps);
    tmxr_poll = t/2;
...
```
This looks good.

Meanwhile:
```
t_stat cpu_reset (DEVICE *dptr)
{
...
sim_clock_precalibrate_commands = pdp10_clock_precalibrate_commands;
sim_rtcn_init_unit (&cpu_unit[0], cpu_unit[0].wait, TMR_RTC);
sim_activate(&cpu_unit[0], 10000);
#if ITS
if (QITS) {
    sim_rtcn_init_unit (&cpu_unit[1], cpu_unit[1].wait, TMR_RTC);
}
#endif
```
Part of this is right, the initial sim_rtcn_init_unit () call, and the sim_activate.
Meanwhile, it is not the lease bit clear what you're trying to do with the stuff in #if ITS #endif.  If there is to be another clock, it MUST have a different timer id (TMR_RTC for both is a problem).  From looking over the code, it seems that this just should be removed.

Then elsewhere in kl10_fe.c we've got:
```
t_stat dte_reset (DEVICE *dptr)
{
    dte_unit[0].STATUS = DTE_SEC;
    dte_unit[1].STATUS = 0;
    dte_unit[2].STATUS = 0;
    dte_unit[3].STATUS = 0;
    cty_done = 0;
    sim_rtcn_init_unit (&dte_unit[3], 1000, TMR_RTC);
    sim_activate(&dte_unit[3], 1000);
    sim_activate(&dte_unit[2], 1000);
    return SCPE_OK;
}
```
This is yet another place that will confuse the internal timing infrastructure since it merely does an init without any calibration steps, AND it again uses the same TMR_RTC value.  This line should just be removed.

Elsewhere in ka10_pd.c there is:
```
t_stat
pd_srv(UNIT * uptr)
{
    int32 t;

    t = sim_rtcn_calb (pd_tps, TMR_PD);
    sim_activate_after(uptr, 1000000/pd_tps);
    if (uptr->PIA_CH & PIA_FLG) {
        uptr->PIA_CH |= CLK_IRQ;
        set_interrupt(PD_DEVNUM, uptr->PIA_CH);
    } else
        sim_cancel(uptr);

    return SCPE_OK;
}
```
Here is a calibration without an init.  the call to sim_rtcn_calb() and the declaration of "int32 t;" should just be removed.  Maybe TMR_PD should also be removed.

These problems had me running in circles trying to track down some unexpected clock behavior while running the KL10 simulator.  An update to the latest SCP stuff would be a good idea.

**Comment by rcornwell** [comment]
Looking at the quantum clock code, I am not sure it ever triggers. I might need to do like I did for the tim_clk for the KL10 to get it to work. The quantum clock is a 1Mhz clock, but I believe it can work with a 250k time base.

The reason for not including more units in the CPU is that they are not user controllable, and as such I don't want to have cpu0 cpu1 etc which would confuse users.

Perhaps a generic timer needs to be added to simh that a simulator could request IRQ's so many times per second.

The kl10_fe.c uses a different timer, I have changed the name to avoid confusion. 

I have added a reset to PD clock.

**Comment by rcornwell** [comment]
Never mind quantum clock comments, the service routine is only to trigger an interrupt. It uses the time remaining on routine to compute results of reading.

**Comment by markpizz** [comment]
I didn't say anything about whether the reset of the logic in the clocks actually works.  I certainly looks like it could.  

simh only needs one calibrated clock, and if a simulator doesn't provide one, then it creates an internal one of it's own under the covers.  This allows sim_activate_after_xxx() apis to have correct delays.

> The reason for not including more units in the CPU is that they are not user controllable, and as such I don't want to have cpu0 cpu1 etc which would confuse users.

Any units with UNIT_DIS in the flags is invisible to users and thus not user controllable and only for use by the simulator's internal functionality.  The only time any such unit's name would be visible is in debug output.  Only a simulator developer would be looking at that.  You could have 3 defined always with no ill effect.  They get used when they get used based on other logic.

> The kl10_fe.c uses a different timer, I have changed the name to avoid confusion.

Just take the sim_rtcn API calls out completely.  This device can perfectly reasonably have an internal clock ticking without calling these APIs.

> Perhaps a generic timer needs to be added to simh that a simulator could request IRQ's so many times per second.

This will work always:

t_stat xxx_svc(UNIT *uptr)
{
sim_activate_after(uptr, 1000000/xxx_tps);
}

**Comment by rcornwell** [comment]
So I don't need to use a separate timer for these clocks?

**Comment by markpizz** [comment]
You could remove all sim_rtcn_xxx API calls and things would work just fine.  You can leave the primary one in the CPU, but my initial comments suggested which ones should definitely be removed.

**Comment by rcornwell** [comment]
Ok... removed them, doing testing.

**Comment by markpizz** [comment]
The only reason you might want one "calibrated clock" is this one:
```
t_stat
rtc_srv(UNIT * uptr)
{
    int32 t;
    t = sim_rtcn_calb (rtc_tps, TMR_RTC);
    sim_activate_after(uptr, 1000000/rtc_tps);
    tmxr_poll = t/2;
...```
Notice that tmxr_poll is derived from this clock's tick delay.  You then can be coscheduling other polling activities based on this which will get synchronized with the clock ticks to avoid extra wakeups or spinning while idle.
The tmxr_poll activity isn't really relevant for 'active' use of TMXR if the device in question is using the internal TMXR completion timing, so sim_activate waits on those TMXR devices are only referenced when there are no active/busy tmxr lines.  The activate times for these cases could be 200000 and you'd never notice.

**Comment by rcornwell** [comment]
Ok... pushed changes out, let me know if there are other problems.
