### ISSUE TITLE
KA10: add support for DC10

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#19]
Systems Concepts disk controller, used on MIT-AI.

This is quite optional.  The RP10 controller works well.

**Comment by rcornwell** [comment]
Don't see a need for this, it would be more productive to add in RH10 support to the KA10.

**Comment by larsbrinkhoff** [comment]
I have an actual use case.  To run a binary version of ITS 724.  It's built for the AI KA10, and uses the Systems Concepts DC-10 disk controller.
