### ISSUE TITLE
KA10: DeCoriolis clock

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#20]
I *think* this is a real-time clock.  Without it, ITS will complain it doesn't know that time it is during boot.

**Comment by rcornwell** [comment]
I need specifications to implement this.

**Comment by larsbrinkhoff** [comment]
I think it's like this: DATAI PDCLK,A sets A to the number of seconds times 60 since the beginning of the year.

**Comment by larsbrinkhoff** [comment]
Made by Paul DeCoriolis according to ITS 1.5 Reference Manual.

**Comment by larsbrinkhoff** [comment]
I'm working on this.  I have added a new PD device to the simulator and implemented the DATAI.

**Comment by larsbrinkhoff** [comment]
@philbudne PDCLK is device code 500.

**Comment by larsbrinkhoff** [comment]
It seems to work.

On first boot, set time with :PDSET.  Maybe shut down properly with :LOCK.

After that, ITS will always know the time and date when booted.

**Comment by larsbrinkhoff** [comment]
@rcornwell, here's my code at its current state:  
https://github.com/larsbrinkhoff/ka10-simh/commit/bf489c09cfec8279e4b5db44b174904de8f7ea1a

Does it need any tweaks?  Will you merge this into your repository?

**Comment by rcornwell** [comment]
Looks ok, does it work and compile without errors? You need to resync your repo before doing the merge.

**Comment by larsbrinkhoff** [comment]
Yes, it works.  I have enabled PDCLKP in ITS and tested with PD on and off.

I submitted a pull request.

**Comment by larsbrinkhoff** [comment]
Fixed by #30.

**Comment by rcornwell** [comment]
Updated to allow KI side to build without this device. Also fixed device so it can be disabled.

**Comment by larsbrinkhoff** [comment]
I haven't forgotten about this.  There are just many other pressing
issues now.
