### ISSUE TITLE
KA10: 340 display

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#22]
Maybe work with @philbudne on this.

ITS applications:

- Exec DDT
- Spacewar!
- PEEK
- MAGDMP
- FED (font editor)
- DECUUO (to run SUDS?)
- 11SIM
- LD10
- PDSET
- SHRDLU (unclear if what we have has display support)

**Comment by philbudne** [comment]
Yes! I'd LOVE to work on the simulated display code for this (ever since I started code for the 340 c. 2003)!

**Comment by larsbrinkhoff** [comment]
I think everything is in place to start this.  ITS works well enough, and there is software that looks like it's using the display.

**Comment by larsbrinkhoff** [comment]
Other graphical displays in use with ITS were E&S and Imlac PDS-1.  But those can wait.

**Comment by rcornwell** [comment]
Is this working?

**Comment by philbudne** [comment]
Yes, stand-alone spacewar runs on a checkout of the master branch!

I haven't tried running the T/S version, or any program using the
display UUOs.  That might (at the very least) require simulating the
MIT PDP-6/PDP-10 device sharing hardware:

$ grep -a DSDEV src/system/its.1648 
IFN DSDP,	DSDEV==20	;DE SELECTION AND INTER COM DEVICE
IFN DSDP,	DSDEVN==24	;DE SELECTION DEV (FOR DEVICES YOU DATAO DEV CODE TO DSDEVN)


Another program I noticed a bit of 340 code in is 11sim:
	.DSTART NULDIS
	.DSTART [-4000+NGDATA-NGBLK,,NGDATA-1]

**Comment by larsbrinkhoff** [comment]
ITS is fully convinced the 340 display requires the use of DSDEV, but it looks like those instructions could be made conditional on DSDP.  It's just two places.

**Comment by rcornwell** [comment]
Is there some instructions I need to add into the simulator?

**Comment by larsbrinkhoff** [comment]
ITS does a DATAO DSDEV,[DSNDIS] to signal when the PDP-10 isn't using the display.  But I don't think there anything needed to be added to the simulator for this.  DATAO to an unknown device is just ignored, right?

**Comment by rcornwell** [comment]
As long as there is no device assigned to a address, it will use the null device. This basically always reads zero and ignores all writes.
