### ISSUE TITLE
KA10: Fix MTY bug

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#224]
MTY input and output will sometimes be garbled.  I confirmed that logging DATAIO will display input on a line that I know is idle.

When I studied the code I see that both mty_input_svc and mty_output_svc can write the MTY_LINE bits in the status register.  I believe the fix should be to sim_cancel both svcs when an interrupt is posted.  I will test this and post a pull request soon.

**Comment by rcornwell** [comment]
Please hold off on a pull request until I do my next pull to the repo.

**Comment by larsbrinkhoff** [comment]
Fixed by #229.
