### ISSUE TITLE
Where can I find UTX and MPX installation tapes for SEL32

### ISSUE THREAD

**Issue by ivannudem** [rcornwell/sims#227]
Dear Developers,
This is a not a issue but some questions. First of all, I want to thank all of your hard work to extend the simh to those historic computers. I'm interested in the SEL32 simulator, and found in the description that it could run UTX2.1a and MPX OS, but I didn't find a link to download them. May I ask where can I download them? Thanks

Best
Ivan

**Comment by AZBevier** [comment]
My name is Jim Bevier, the developer and maintainer for the SEL32 simh project.  My local sims github archive contains the installation tapes/disks for UTX 2.1A and UTX 2.1B.  Also there is a tape/disk for MPX.1X.   The MPX 3.X install tape is in progress.  https://github.com/azbevier has a sims and SEL32-rcsim archive.  The sims archive is my local copy while the SEL32-rcsim is the current simh release.  E-mail me if you have any questions.  AZBevier@gmail.com
