### ISSUE TITLE
KA10: TECO crash

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#23]
I built and dumped a new TECO.  However, there's a problem when I start it.  This message is printed over and over:

    ERROR WHILE ENTERING ERROR HANDLER! POPPING TO TOP LEVEL.

To reproduce:

- :midas sysbin;_.teco.; teco >
- :job teco
- :load sysbin; teco bin
- purify$g
- *press Enter to save in .TECO.; TECPUR 1212*
- :kill
- :link sys; ts teco, .teco.; tecpur >
- :teco

**Comment by larsbrinkhoff** [comment]
TECO source code is in the latest update of `min-source.tape`.

**Comment by rcornwell** [comment]
Not sure what is going on here... this is an error in Teco. It is triggered in QBGET with the LUUO37. I have not determined where QBGET is coming from.  The TLZE instruction is skipping, thereby forcing the error. This might be due to AOB (and friends) on the KA being different from the KI and above.

**Comment by larsbrinkhoff** [comment]
Running the unpurified TECO seems to work.  At least I get a banner message and a prompt.

There's something wrong with the purified and dumped TECO.  When loaded, DDT can't find its symbols.

**Comment by larsbrinkhoff** [comment]
I say this looks related to #34.

**Comment by larsbrinkhoff** [comment]
Note that TECO built and dumped in KS ITS doesn't work in KA ITS.

**Comment by larsbrinkhoff** [comment]
EMACS does work.

**Comment by rcornwell** [comment]
This helps, I will try working on Purify issues later this week.

**Comment by rcornwell** [comment]
This should be fixed with latest commit.

**Comment by larsbrinkhoff** [comment]
Yes, TECO starts fine.
