### ISSUE TITLE
KA10: Data Disc displays

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#236]
WAITS raster displays.

https://www.saildart.org/HM[H,DOC]
https://www.saildart.org/FACIL.TED[H,DOC]
https://stacks.stanford.edu/file/druid:hb976hq8639/uuomanual.pdf, Appendix 2

**Comment by larsbrinkhoff** [comment]
I have started on this.  Assign me if you like.

**Comment by larsbrinkhoff** [comment]
I think this is close to the SAIL hardware.  
http://www.bitsavers.org/pdf/dataDisc/Television_Display_System_Reference_Manual_Jul69.pdf

**Comment by larsbrinkhoff** [comment]
So far so good.  CC @bgbaumgart 
![data-disc](https://user-images.githubusercontent.com/775050/109052538-01cc9700-76dc-11eb-9c97-02fb645b011e.png)

**Comment by larsbrinkhoff** [comment]
I'm going to have to mess with the DKB device too, to provide many keyboard inputs.

**Comment by larsbrinkhoff** [comment]
From the TDS manual on Bitsavers.  A sample of the 5x7 font.  The SAIL hardware would have the extended ASCII characters added.

![tds1](https://user-images.githubusercontent.com/775050/109112377-d5943300-773a-11eb-80e2-3420678fbff8.png)
![tds2](https://user-images.githubusercontent.com/775050/109112383-d88f2380-773a-11eb-88a8-765e382c754a.png)

Bonus feature: control panel.  Bruce, do you recognize this?
![tds3](https://user-images.githubusercontent.com/775050/109112414-e775d600-773a-11eb-8362-b452c3def9e2.png)

**Comment by larsbrinkhoff** [comment]
I compared the font sample above with the Knight TV characters, and many match exactly.  Some have minor differences.

**Comment by larsbrinkhoff** [comment]
I have something that is like 80% working now.  Various display issues, maybe some in the sim_video part.
![dd](https://user-images.githubusercontent.com/775050/109382518-32315280-78e1-11eb-8de1-1a5f7c59daad.png)

**Comment by larsbrinkhoff** [comment]
After an - ahem brief - hiatus, I'm picking this up again.  A sim_video problem has been fixed, so now multiple DD windows will update properly.  I added code to get keyboard events from the DD windows even if the III is disabled (previously all events went through the vector display library).

A new problem pas popped up: it's no longer possible to have both III and DD displays.

When I try to log in, some previously unimplemented display commands are used.  They will be added soon.

**Comment by bgbaumgart** [comment]
Rcornwell and LarsB
-
Acknowledged - - I am still working on SAIL disk images but I will be invisible for all of October while touring for four week in Scotland and Wales.
International travel during a pandemic is a red tape nightmare - we have had our vaccinations and booster shots but still have to test and re-test frequently.
-
Bruce Baumgart
BGB

**Comment by larsbrinkhoff** [comment]
Being added in pull request #300
