### ISSUE TITLE
KL10?: Samson box

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#237]
Add emulator of Samson box.

Hopefully we can use Bill Schottstaedt and @mmcnabb's code: https://github.com/mmcnabb/sam

Will need later version of WAITS disk image, maybe a KL10 version?

**Comment by rcornwell** [comment]
Not doing KL10 waits support.

**Comment by larsbrinkhoff** [comment]
Suggest reopening and assigning to me.  Let's proceed on the assumption
it can be used with a KA10.

**Comment by larsbrinkhoff** [comment]
Besides, I might try KL10 myself if I get bitten hard by the WAITS bug.

**Comment by larsbrinkhoff** [comment]
From https://searchworks.stanford.edu/articles/aph__90443564/pdf/fulltext

[life_sam.pdf](https://github.com/rcornwell/sims/files/6074690/life_sam.pdf)

**Comment by larsbrinkhoff** [comment]
http://www.bitsavers.org/pdf/systemsConcepts/Digital_Synthesizer/

**Comment by larsbrinkhoff** [comment]
![sam](https://user-images.githubusercontent.com/775050/109783201-05937880-7c0a-11eb-8a2f-8ee7931d34d4.png)
