### ISSUE TITLE
KA10: Idle support

### ISSUE THREAD

**Issue by rcornwell** [rcornwell/sims#26]

**Comment by rcornwell** [comment]
This is working under TOPS10. ITS does not idle well with the high speed quantum clock.

**Comment by rcornwell** [comment]
This should now work on ITS. I stopped the quantum clock when going idle and restart it when coming out of idle.

**Comment by larsbrinkhoff** [comment]
Great!  An idling ITS takes about 1-2 % host CPU on one of my machines.
