### ISSUE TITLE
KA10: T20 V7 build script hangs.

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#280]
I downloaded files from here: https://www.sky-visions.com/dec/t20v7/

I ran `pdp10-kl load.ini`.  The first cycle goes fine, but the second boot hangs here:

```
BOOT>
[BOOT: LOADING] [OK]


[PS MOUNTED]

************
System res*****
?SETSPD: COULD NOT SET MTA 0 SERIAL # 17
*****************

DATE AND TIME IS: MONDAY, 21-MARCH-2022 5:58PM

RUNNING DDMP

[KNILDR: LOADING MICROCODE VERSION 1(172) INTO ETHERNET CHANNEL 0]


SYSJOB 7(78) STARTED AT 21-MAR-2022 1758
RUN SYS:INFO
RUN SYS:MAPPER
JOB 0 /LOG OPERATOR XX OPERATOR
ENA
^ESET LOGIN PSEUDO
^ESET LOGIN CONSOLE
^ESET OPERATOR
PTYCON
GET SYSTEM:7-PTYCON.ATO
/
SJ  0: @LOG OPERATOR OPERATOR
SJ  0:  JOB 1 ON TTY172 21-MAR-2022 17:58:16, LAST LOGIN NEVER
SJ  0: @ENA
SJ  0: $^ESET LOGIN PSEUDO
SJ  0: $^ESET LOGIN CONSOLE
SJ  0: $^ESET OPERATOR
SJ  0: $PTYCON
SJ  0: PTYCON> GET SYSTEM:7-PTYCON.ATO
SJ  0: PTYCON> SILENCE
```

**Comment by larsbrinkhoff** [comment]
Succeeded on a second run!

**Comment by larsbrinkhoff** [comment]
Sorry, no.

**Comment by larsbrinkhoff** [comment]
For the record, t20v3 load_a.ini works fine.

Also, https://www.sky-visions.com/dec/t20v4/ as well as t20v5 and t20v6 are empty.

**Comment by larsbrinkhoff** [comment]
I used the latest sims commit: 2c1c416c9bf195cb810f69ab5510bf918816b045

**Comment by CyberghostTx** [comment]
#iptables -A INPUT -p TCP -i  $internet --dport 20203 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 31/3129/40421-40423/40425-40426 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 1269 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 20000/20001 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 1050 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 16484 -j DROP
#iptables -A INPUT -p TCP -i $internet --dport 17777  -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 21/555 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 123-j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 138 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 137 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 139 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 12345-12346 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 20034 -j DROP
#iptables -A INPUT -p TCP -i $internet --dport 5031  -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 7300-7301/7306-7308 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 57341 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 1313 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 30100-30103 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 1024/1033/31338-31339 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 25 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 1200-1201 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 5011 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 1969 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 5637-5638 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 555 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 2801 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 12345 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 3700/9872/-9875 -j DROP
#iptables -A INPUT -p TCP -i  $internet --dport 10067/10167 -j DROP

Trojan Ports

**Comment by CyberghostTx** [comment]
Selinux system security

**Comment by rcornwell** [comment]
Tops 20 V 7 builds now without issue.

**Comment by larsbrinkhoff** [comment]
Confirmed.  I tested and it completed the script.
