### ISSUE TITLE
KA10: TOPS-10 build script problem.

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#281]
Downloaded files from here: https://www.sky-visions.com/dec/tops603

Ran `pdp10-ka load.ini` with latest sims commit 2c1c416c9bf195cb810f69ab5510bf918816b045.

Full transcript; hangs on last line `?NOT AN STR - TRY AGAIN`.

```
KA-10 simulator V4.0-0 Current        git commit id: 2c1c416c
On Processing at Do Nest Level: 1 is disabled

Logging to file ".log"
/home/lars/src/build-tenex/tops603/load.ini-29> at -r mta0 tapes/mon.tap
%SIM-INFO: MTA0: unit is read only
%SIM-INFO: MTA0: Tape Image 'tapes/mon.tap' scanned as SIMH format

BOOTM V4(17)

BTM>monka[1,4]

KA603 04-21-78
WHY RELOAD: hard
DATE: 04-21-78
TIME: 1000

STARTUP OPTION: refresh

%CONTROLLER RPA IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, OR 2)DOWN? (TYPE #)

2

%CONTROLLER DPA IS OFF-LINE
DO YOU WANT IT TO BE 1)ON-LINE, OR 2)DOWN? (TYPE #)

2

?NO UNITS IN ACTIVE SWAPPING LIST

?NO UNITS IN ACTIVE SWAPPING LIST
TYPE STR NAME TO BE REFRESHED(CR IF NONE, ALL IF ALL)
dskb
?NOT AN STR - TRY AGAIN
```

**Comment by larsbrinkhoff** [comment]
https://www.sky-visions.com/dec/tops603 ran `pdp10-ki load.ini` got:

```
BOOTM V4(17)

BTM>monka[1,4]

KA603 04-21-78
?THIS MONITOR WAS BUILT FOR A KA10 AND WILL NOT RUN PROPERLY ON A KI10

HALT instruction, PC: 147423
```

Isn't the script supposed to detect KI10?

**Comment by larsbrinkhoff** [comment]
Patched script to hardcode for KI10.  I still get `?NOT AN STR - TRY AGAIN` like for KA10.

**Comment by larsbrinkhoff** [comment]
TOPS-10 5.x this time: https://www.sky-visions.com/dec/tops503

Minor comment: Readme could say to bunzip the tape images.

`setup.ini` and `mon530.ini` work fine.

**Comment by larsbrinkhoff** [comment]
TOPS-10 7.03 and 7.04 seem ok on pdp10-kl.

The scripts do not work with pdp10-ks.

**Comment by rcornwell** [comment]
For Tops 10 6.03 did you read the README.txt file?

 pdp10-xx load.ini xx dsk   So for KA10 with RP10 drives use pdp10-ka load.ini ka dp

**Comment by larsbrinkhoff** [comment]
I downloaded the tops603.zip file, read the README.txt, and followed the instructions.  Successfully tested KA10 and KI10, didn't run KL10.
