### ISSUE TITLE
KA10: RP10 CONI bit 30 problem

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#286]
TENEX checks RP10 CONI bit 30 and thinks it's an error if it's set.

The manual seems to say it should *only* be set if a CCW transfer was explicitly requested with CONO.
http://www.bitsavers.org/www.computer.museum.uq.edu.au/pdf/DEC-10-H5EC-D(1)%20PDP-10%20RP10%20Disk%20Pack%20Synchronizer%20Maintenance%20Manual%20Volume%201.pdf

![Screenshot from 2022-04-25 10-11-36](https://user-images.githubusercontent.com/775050/165047615-672d681f-6efe-46d3-b8c2-b8f51a047d04.png)
![Screenshot from 2022-04-25 10-12-33](https://user-images.githubusercontent.com/775050/165047806-8fbf62ec-2296-49ca-841e-ac1afabb0425.png)

**Comment by larsbrinkhoff** [comment]
When I change kx10_dp.c as per above, TENEX started from SYSGO$G or SYSGO1$G will successfully boot and start \<SYSTEM>EXEC.SAV.

I checked ITS, and it does not check RP10 CONI bit 30.  I have not checked TOPS-10.

**Comment by larsbrinkhoff** [comment]
TM10B request control word:

![Screenshot from 2022-04-25 14-36-29](https://user-images.githubusercontent.com/775050/165090236-8a6ba8ff-46de-4a86-85b6-797828ffc458.png)
![Screenshot from 2022-04-25 14-37-07](https://user-images.githubusercontent.com/775050/165090301-6e6d73a3-be26-4d01-974d-7fd43dc01d21.png)
From http://www.bitsavers.org/pdf/dec/pdp10/periph/DEC-10-I4AA-D_TM10_Maint_Aug68.pdf

**Comment by larsbrinkhoff** [comment]
Steps to repeat: 

1. Get disk images here: https://github.com/larsbrinkhoff/build-tenex/tree/master/media
2. Boot with pdp10-ki and https://github.com/larsbrinkhoff/build-tenex/blob/master/tenex.do
3. At EDDT, type `sysgo1$g`

Actual (wrong) output will be `INTERRUPT AT 0`

Expected output is

```
TENEX RESTARTING, WAIT... NO CHECKDSK

TENEX IN OPERATION

 SUMEX-AIM Tenex 1.31.82, SUMEX-AIM EXEC 1.51
 ENTER DATE AND TIME AS MM/DD/YY HH:MM -- 
```

**Comment by rcornwell** [comment]
Fixed
