### ISSUE TITLE
KA10: Boot MAGDMP off magtape

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#29]
Last time I tried this, it didn't work.

Steps to reproduce:

1. Start simulator with the usual configuration for ITS
2. Attach magdmp.tap to mta0.
3. b mta0

**Comment by rcornwell** [comment]
I will try and fix this once we get ITS loaded from tape correctly. It is probably a bug in MAGFRM.

**Comment by rcornwell** [comment]
This appears to be working the remaining bugs are related to how tapes are generated.
