### ISSUE TITLE
Help with IMP device for PDP10

### ISSUE THREAD

**Issue by afberendsen** [rcornwell/sims#299]
Hi

I am having some issues to use the IMP device in the PDP10 simulators.

1. What is the difference between the IP and HOST addresses?
2. I have a DHCP server in place. Setting the interface to use DHCP (SET IMP DHCP), based on the source code, when using the ATTACH command (ATTACH IMP eth12), it should bring a valid IP address to the IMP interface (SHOW IMP). However, none of the values (IP, GW, HOST) are changing.

**Comment by rcornwell** [comment]
HOST is the address of the ITS system (or whatever the IMP is connected too). IP is the IP address that the IMP will respond to on the local net.

Not sure why it is not getting a proper IP address. The DHCP request should occur when the device is reset, or as soon as it is attached.

**Comment by afberendsen** [comment]
I cannot make it work. Any suggestions?

```
sim> set imp dhcp
sim> show imp
IMP     MAC=00:00:02:31:83:47, MPX=0, IP=0.0.0.0/0
        GW=0.0.0.0, HOST=0.0.0.0, DHCP Server IP=0.0.0.0, State:OFF, Waited 0 seconds
        not attached, DHCP, MIT
sim> attach imp eth12
%SIM-INFO: Eth: opened OS device \Device\NPF_{EDF7020B-3C8F-4980-866D-2CF83E8CF66F} - Intel-2.5Gb
sim> show imp
IMP     MAC=00:00:02:31:83:47, MPX=0, IP=0.0.0.0/0
        GW=0.0.0.0, HOST=0.0.0.0, DHCP Server IP=0.0.0.0, State:OFF, Waited 0 seconds
        attached to eth12, DHCP, MIT
sim> show imp
IMP     MAC=00:00:02:31:83:47, MPX=0, IP=0.0.0.0/0
        GW=0.0.0.0, HOST=0.0.0.0, DHCP Server IP=0.0.0.0, State:OFF, Waited 0 seconds
        attached to eth12, DHCP, MIT
sim>
```

**Comment by rcornwell** [comment]
The DHCP address is not set until the simulator is running. The timing is handled by device timeouts. I will have to think about how to handle disabling DHCP after attach. This is not truly an error, what will happen is that the DHCP lease will not be released nor refreshed.
