### ISSUE TITLE
9AP does not boot

### ISSUE THREAD

**Issue by rsanchov** [rcornwell/sims#3]
Hi
I'm trying to run 9AP on I7090 but fails on booting.
May be I'm doing something wrong?

Many thanks in advance
Best regards
Roberto

(Image attached)
[9AP.zip](https://github.com/rcornwell/sims/files/673782/9AP.zip)

**Comment by rcornwell** [comment]
Can you provide more information. Like a sample run or instruction history. 9AP runs for me.

**Comment by rsanchov** [comment]
Hi
I've attached to the issue a zip file with all the environment I'm usingI attach it again on this email. On run I got:
E:\IBM 7000\sw\9AP>..\i7090 asm.iniIBM 7090 simulator V4.0-0 Beta        git commit id: ff95fb8e
CR: unit is read only
Attempt to access offline unit MTB0HALT instruction, IC: 00000 (  000016000003   HTR 00003)
asm.ini-16> assert IC =03176
Assertion failed
sim>
I think I'm not interpreting the directions in readme.txt in the right way
RegardsRoberto 

    On Tuesday, December 27, 2016 2:20 PM, Richard Cornwell <notifications@github.com> wrote:
 

 Can you provide more information. Like a sample run or instruction history. 9AP runs for me.—

**Comment by rcornwell** [comment]
The error message indicates that it is looking for a tape on MTB0 

What is unclear is where you got the 9ap.bcd file from. 

I notice that the 9ap.tp file is empty. 

If you grab the 9ap.bcd tape off my web site, then change the ini file to the following:
  at mtb0 -f p7b 9ap.bcd

use "mkbcdtape" to create your input tape. And attach it as mta0. 

Boot would be from mtb0, not the card reader.

if you want your input from the card reader use dep sw1 1.

You appear to have a very old copy of my readme file. I found out I had the sense switches backwards many years ago. The notes on my web site are correct. Let me know if you need mkbcdtape and listtape and I will put them up for you.

**Comment by rsanchov** [comment]
Hi Richard
Thanks for your directions!. Now I can assemble the diag programs and I get same result byte by byte than the .cbn on the web.
But the web adverts that .cbn decks miss a loader. So  ... how can I execute an assembled .cbn?
I've tried boc.cbn but without success.
at cr0 -f cbn boc.cbn
at cr1 -f cbn prog.cbn
boot cr0
at cr0 -f cbn boc.cbn
boot cr0
at cr0 -f cbn prog.cbn
go
Any help welcomeRegardsRoberto
 

    On Tuesday, December 27, 2016 7:13 PM, Richard Cornwell <notifications@github.com> wrote:
 

 The error message indicates that it is looking for a tape on MTB0What is unclear is where you got the 9ap.bcd file from.I notice that the 9ap.tp file is empty.If you grab the 9ap.bcd tape off my web site, then change the ini file to the following:
at mtb0 -f p7b 9ap.bcduse "mkbcdtape" to create your input tape. And attach it as mta0.Boot would be from mtb0, not the card reader.if you want your input from the card reader use dep sw1 1.You appear to have a very old copy of my readme file. I found out I had the sense switches backwards many years ago. The notes on my web site are correct. Let me know if you need mkbcdtape and listtape and I will put them up for you.—

**Comment by rsanchov** [comment]
Hi
I've made a .ini file with your directions (thanks again), I send it to you in the case you want to put it in your web to help any other novice in i7090 world that can have troubles as me.
I will try to do the same for UASAP
I also see that BOC.LST is a program from 1952! should be for 701!! awesome!.Do you know how this program is ussed?
Best regardsRoberto

**Comment by rcornwell** [comment]
Hi sorry for the delay getting back to you, been dealing with kidney stones. Anyway you can concat the .cbn and .bcd files together. They have internal record delimiters.

**Comment by rcornwell** [comment]
Using wrong version of sim_card.[ch].
