### ISSUE TITLE
Irrelevant Include files shoud be removed

### ISSUE THREAD

**Issue by markpizz** [rcornwell/sims#303]
PDP10/ka10_ten11.c has to system include files that serve no purpose:
fcntl.h
and sys/types.h

The build succeeds without these on all platforms.

**Comment by rcornwell** [comment]
No longer there.

**Comment by markpizz** [comment]
Lines 34 and 35 of ka10_ten11.c are still in https://github.com/rcornwell/simh/ master branch...
