### ISSUE TITLE
kl10 tops10 eddt sometimes doesn't seem to accept keyboard input

### ISSUE THREAD

**Issue by jeffgunter** [rcornwell/sims#305]
my apologies if this is the wrong way to submit a possible bug or if this is a known problem, or not worth reporting.  i also apologize for the casual and only barely coherent writing style.  please scold me as needed.

For PDP10 KL simh, TOPS10 EDDT sometimes seems not to work very well.  if system startup is complete, or nearly complete, then EDDT does not appear to accept input, and so it becomes difficult to debug TOPS10 and it's interaction with simh.

The problem might be the code at kl10_fe.c in t_stat dtei_svc (UNIT *uptr).

in the paragraph "_/* If Monitor input, place in buffer */_, at the if statement, the value of optr->STATUS is 4000012.  Not sure what the 12 means exactly, but the 4000000 appears to mean secondary protocol, which I think is normal. Specifically, when EDDT first starts, STATUS is 4000001, meaning the FE is in secondary (at least according to STATUS), and I think EDDT tries to make the FE "leave primary" (which i take to mean "enter secondary") when interaction like breakpoints happen, so I think it is normal for the FE to be in secondary protocol.

in this if statement:
    if ((optr->STATUS & (DTE_SEC|DTE_MON)) == (DTE_SEC|DTE_MON) &&
         not_empty(&cty_in) && M[SEC_DTMTI + base] == 0) {
the code seems to be checking if the FE is in secondary protocol or monitor mode (not sure what monitor-mode is, something for kldcp perhaps?).  The problem might be that STATUS is 4000012 (which when masked with SEC!MON is 4000000), but is being compared to 4000001, and doesn't match, so the condition fails, so the next character is  not written to the ept communication words, so EDDT does not see the typed input, even tho they're in the cty input buffer.

i'm not a C programmer, and i'm not a kl10 whizard, and not a TOPS10 expert -- so i'm not so sure what the *proper* fix for this is, but since i'm not aware of TOPS10 using monitor mode, i locally changed the check to be the DTE_SEC bit only, so the == matches.  this seems to make EDDT work (better).

**Comment by rcornwell** [comment]
Yes this is the correct place to request this. I myself don't use EDDT so not sure how to test it. I tried to use it but whenever I attempted to set a break point it would not find the symbol. If you can give me a trace of some commands to show the issue?

**Comment by jeffgunter** [comment]
sure.

  

not exactly sure whether you want how to see what I'm seeing work/fail,

or whether you want to see proof of what the emulator is seeing (the sim_debug commands i added?),

or whether you want to see the code i changed locally... ?

so below I've included just a more visual representation of the problem happening; do not hesitate to request something else:
  
  
    
  
  here's me running the locally changed simh, and loading 7.04 with eddt. (if you don't have it (I'm sure you do!), i can send you or point you at the disks i am using that have 704non.exe on them.)
  
  
    
  
  the /e tells boot to enter eddt.  i typed rubout, or possibly ^U, already don't remember.  but then i typed xyz followed by ^U.
  
  
    
  
  "rubout" is octal 177, generated by the delete key above the | key on most windows keyboards.  and ^U means control-U.  $ means escape key, around the TAB key on most keyboards.
  
  pretty sure you know all that, just covering bases.
  
  
    
  
  then DEBUG$G
  
  
    
  
  then waited until i got the dot from tops10
  
  
    
  
  then i typed ^D  to call up eddt.  then i typed a few rubouts.
  
  
    
  
  if i use just the "standard" release, then the rubouts after the ^D do nothing at all.  and i cannot do a $P to proceed from the breakpoint.
  
  
    
  
  
    
    
    # ./pdp10-kl    <--- to clarify, this is the local changed pdp10-kl with "fix".
    
    
      
    
    KL-10 simulator Open SIMH V4.1-0 Current        simh git commit id: 5c112d0e
    
    sim> do setup  <-- just sets up some disk drives and the ^ escape
    
    sim> do decboot <-- a version of the standard boot that is just DEP commands
    
    BOOT V4(100)
    
    
      
    
    BOOT>704non/e
    
    [Loading from DSKA:704NON.EXE[1,4]]
    
    EDDT
    
    XXX you can't see them but i typed rubouts here and got XXXs
    
    XXX
    
    XXX
    
    xyzXXX  typed xyz and then ^U here
    
    debug$g  started up tops10, $ is escape key
    
    
      
    
    TOPS-10 704 No Network 11-Nov-93
    
    Date: 26-sep-2023
    
    Time: 1602
    
    [Rebuilding the system search list from the HOM blocks]
    
    
      
    
    [Rebuilding the active swapping list from the HOM blocks]
    
    
      
    
    [Rebuilding the system dump list from the HOM blocks]
    
    
      
    
    To automatically log in under [1,2] type "LOGIN"
    
    
      
    
    TOPS-10 704 No Network Tuesday 26-Sep-123 16:02:15
    
    
      
    
    .(so got the dot, then typed ^D here)$0B>>1,,RICD#+17/   MOVSI R,CDSAV#   XXX   XXX
    
    without fix, do not get the XXX's
    
    after the dot from tops10, typed ^D to invoke EDDT, then a couple of rubouts, which echo as XXX
    
    with standard release, i see just the CDSAV# and simh/eddt seems to ignore further input
    
    
    certain it does not matter, but fwiw, here is setup
  
  
    # cat setup
    
    set console wru=034
    
    set cpu kl10b 1024k
    
    set rpa rh20
    
    set rpa0 rp06
    
    set rpa1 rp06
    
    set rpa2 rp06
    
    set rpa3 rp06
    
    att rpa0 twonky-dska-simh
    
    att rpa1 dskc.dsk
    
    att rpa2 dskb.dsk
    
    att rpa3 dskz.dsk  fwiw, dskz is empty but has very large swapping space and extra crash.exe
    
    
      
    
    -jfg
    
    
      
    
    ------ Original Message ------
       Received: 11:42 AM EDT, 09/26/2023

**Comment by rcornwell** [comment]
My problem is that I don't use EDDT so am not familiar with how to get it to fail or how it should work. I replaced the line: kl10_fe.c#1796 with:
    if ((optr->STATUS & (DTE_SEC|DTE_MON)) != (0) &&
if this works let me now.

`sim> cont
%SIM-INFO: SIGINT will be delivered to your debugger when the ^F character is entered
BOOT V4(76)

BOOT>/E
[Loading from DSKB:SYSTEM.EXE[1,4]]
EDDT
$XXX
xyzXXX
debug$tgg\t\$\g\
U
debug$g

KL704 19-Dec-88
Date: 03-19-90
Time: 1100
[KLNI microcode %1(172) loaded on NIA20 564]
[Rebuilding the system search list from the HOM blocks]

[Rebuilding the active swapping list from the HOM blocks]

[Rebuilding the system dump list from the HOM blocks]


KL704 Monday 19-Mar-90 11:00:15

.
.^C


..$0B>>1,,RICD#+17/   MOVSI R,CDSAV#   
^D?
cdsav#?
savexe/   SKIPN T1,.JDAT+17   $b   
$x
   R/   CDSAV#,,0   CDSAV#
1,,RICD#+20/   BLT R,R   $x
   R/   P   R
1,,CDPAT/   POPJ P,0   $x
   P/   .UUPMP+605,,C2PD1+5
<JUMP>
1,,RECIN5#+6/   POPJ P,0   
`

I am using Tops 10 7.04 build with my build scripts.

**Comment by rcornwell** [comment]
What I need is steps showing how it should behave that I can run on my simulator to test. If you want to include where it is going wrong with my simulator that is a help. To fix an error I need to be able to reproduce it.

**Comment by rcornwell** [comment]
Pushed out some fixes... Let me know if they work.

**Comment by jeffgunter** [comment]
that was quick!  i'm ashamed to admit i'm not sure what info you need from me.  english *is* my first language, but i'm sadly slow at communications :(

your change is basically what i did, so it looks fine to me, and it seems to work in your example.   

in the failing case, without the code change, do the /e & debug$G thing.  wait until tops10 prints the dot.  then type ^D.  you will get to the zero breakpoint.  then type _anything_ -- it does not echo because the STATUS bits don't match.  tops10 looks dead because you can't get it to do anything - eddt is running and there is no way from the keyboard to get it to proceed.

you don't have to really wait until the dot, i just do from habit.

in the succeeding case, with the code change, do the /e & debug$G thing.  wait until tops10 prints the dot.  then type ^D.  you will get the zero breakpoint.  now you type something like "P/" and this will show the tops10 stack pointer.  or any of the things you already typed in your example.  or $P to proceed from the breakpoint.  you could then type a couple of carriage returns and expect to get the tops10 dot(s).

if you can type a character and get any response at all, the change is working.  without the change, the input was never passed onto the EPT  magic locations so eddt/tops10 could never act on it.

your sample shows proof it works, because i don't think you would have been able to produce this (or ANY) output if it had not:
^D?
cdsav#?
savexe/ SKIPN T1,.JDAT+17 $b
$x
R/ CDSAV#,,0 CDSAV#
1,,RICD#+20/ BLT R,R $x
R/ P R
1,,CDPAT/ POPJ P,0 $x
P/ .UUPMP+605,,C2PD1+5

1,,RECIN5#+6/ POPJ P,0

thank you for your help,
your fan,
-jfg

**Comment by rcornwell** [comment]
If it and the save file problem are working I will push the changes to the main open-simh repository.

**Comment by jeffgunter** [comment]
to the best of my knowledge, both issues are resolved.
 thanx!
