### ISSUE TITLE
kl10 simh console doesn't seem to always like AC 17

### ISSUE THREAD

**Issue by jeffgunter** [rcornwell/sims#307]
sim> dep 16 move 17,1
Invalid argument
sim> dep 16 move 15,1
sim> dep 16 blt 17,1
Invalid argument
sim> dep 16 movem 17,1
Invalid argument
sim>

**Comment by rcornwell** [comment]
First you need -m to input assembly language. Also registers are FM there technically is memory at address 0-20. But I am unsure why you are getting invalid argument.

**Comment by rcornwell** [comment]
Fixed it. You need to use FM[16] to modify a register.
