### ISSUE TITLE
kl10 maybe pmove/pmovem don't always use physical memory addresses

### ISSUE THREAD

**Issue by jeffgunter** [rcornwell/sims#308]
my tops10 doesn't finish startup without dying.

the problem seems to be this code:
     setz t1,
     pmovem t1,[0]
     pmovem t1,[1]

these instructions _should_ i think zero unmapped physical memory locations 0 and 1, but these instructions _seem_ to  zero AC0 and AC1, and AC1 is the kernel stack pointer, so that becomes a problem.

this code worked as described on my sc40, and my klh10;  it zeroes unmapped physical memory locations 0 and 1.  under simh it zeroes fast memory locations 0 and 1.  

-jfg

**Comment by rcornwell** [comment]
I will have to check up on how pmove should work.

**Comment by rcornwell** [comment]
Where is this code in the source? I can't find my Tops 10 uses PMOVE at all.

**Comment by jeffgunter** [comment]
Your tops10 doesn’t do it.   Mine does during sysini.   We made several modifications to tops10, which I think is not terribly unusual.  Think more compuserve than vanilla.FYI we keep several tracking bits of data in supershadow acs (ie low physical memory like 0 & 1) which will be in the dump if a crash happens.  We use pmovem because we also write protect exec page zero during normal operations since more than one bug happens specifically because a clobbered index ac was being used and low memory got overwritten;  we get a page fault in that situation instead; having the page fault words helps debugging. I’ve gotten this far in trying to get our kernel running by just jfcl’ing those pmovem instructions for now and in this case can live that way forever; you are welcome to leave things as they are.  I’ll mind my own business going forward.  :)Thanx for your help,-jfgSent from my iPhoneOn Sep 27, 2023, at 17:27, Richard Cornwell ***@***.***> wrote:﻿
Where is this code in the source? I can't find my Tops 10 uses PMOVE at all.

**Comment by rcornwell** [comment]
Actually I believe you are correct. I have fixed the issue, but have to test everything since the code is used by all processors.

**Comment by rcornwell** [comment]
Pushed a fix out there... give it a try and let me know. Also since you mentioned you have a SC-40, do you have any docs on exec mode or devices for SC-40?

**Comment by jeffgunter** [comment]
i will give it a shot.

  

yes, i acquired an sc40,  but i don't have much specific documentation, beyond our code.  i might be able to answer specific questions either from memory (mine, not the sc40s), or from our existing code.  mike/stew have suggested a couple of times they would/could supply documentation, but time moves more slowly in vegas; i haven't seen any.


  

the real expert would be Fred Wright, as he worked (or maybe is working) with scgroup; think he did some sc40 sa channel ucode upgrades to support 512 byte block sizes for the museum(s) (or maybe stewart did that ... ?).  also, there must surely be some compuserve people that are reeeeeal whizes on sc40s.  lastly, cory smolski; i've lost contact with them, and am not sure on name's spelling.


  

-jfg
  
  
  
  ------ Original Message ------
     Received: 08:22 PM EDT, 09/27/2023

**Comment by jeffgunter** [comment]
if i use the console command "e" (examine i think?) is the address i give physical or does it go thru one of the paging registers?  perhaps phys, UB or EB, depending on pager enabled, and mode?  can i control which address space is used?

  

ie: does

e <7 digit address>

look at unmapped memory, or does it go thru on the paging registers and associated map(s) ?


  

sorry to be so dim.


  

-jfg
  
  
  
  ------ Original Message ------
     Received: 08:22 PM EDT, 09/27/2023

**Comment by rcornwell** [comment]
examine uses real physical memory.

For SC-40 my question is about how the paging table worked (for extended paging). I kind of worked it out, but code does not run correctly. Use direct email for sc-40 or create a issue about adding sc-40 support to pdp10 simulator.

**Comment by jeffgunter** [comment]
thanx for the reply.  dropped an email to the address alt.pdp10 lists as your email.  scold me as appropriate with correct contact procedures.

  
  -jfg
    
    
    
    ------ Original Message ------
       Received: 09:28 PM EDT, 09/27/2023

**Comment by rcornwell** [comment]
My email is in my profile. Don't read yahoo address anymore. :-)

**Comment by jeffgunter** [comment]
Ok. Will resend when I get home.Sent from my iPhoneOn Sep 27, 2023, at 23:22, Richard Cornwell ***@***.***> wrote:﻿
My email is in my profile. Don't read yahoo address anymore. :-)

**Comment by rcornwell** [comment]
Does the fix I pushed solve your problem?

**Comment by jeffgunter** [comment]
I will check when I have access; I am on the road for the next 10 hours or so.Sent from my iPhoneOn Sep 28, 2023, at 08:39, Richard Cornwell ***@***.***> wrote:﻿
Does the fix I pushed solve your problem?
