### ISSUE TITLE
simh kl10 possibly does not know about OWGBP during 

### ISSUE THREAD

**Issue by jeffgunter** [rcornwell/sims#311]
this code runs in exec mode in section 2, and references a byte pointer in section 4.  (it's part of our equivilent of, er, scnser)

DELT1A:
        SETO    T1,             ;BACK UP BYTE POINTER
        ADJBP   T1,TDBIPT(F)    ;FOR INPUT PUTTER
        MOVEM   T1,TDBIPT(F)

the byte pointer is a one-word-global-byte-pointer:
710004,,50574

the adjbp doesn't seem to change the byte pointer at all.

.abc
$1B>>DELT1A/   SETO T1,0   $x   _** <-- so i typed "abc" at the monitor dot, then typed rubout to make this happen**_
   T1/   -1
DELT1A+1/   IBP T1,JOBBLT+2(F)
f[   123501
jobblt+2+123501[   710004,,53163  _**<-- byte pointer before adjbp **_
$x
   T1/   22&11 4,,53163   2,,TTYTDB+47/   22&11 4,,53163
DELT1A+2/   MOVEM T1,JOBBLT+2(F)   t1[   710004,,53163 _**<-- byte pointer after adjbp **_

by my calculation, the byte pointer should have changed to 700004,,53163

-jfg

**Comment by rcornwell** [comment]
Can you create a test program and put it on a backup tape?

**Comment by jeffgunter** [comment]
I can try.  Again I am on the road so might take an hour +Sent from my iPhoneOn Sep 30, 2023, at 14:34, Richard Cornwell ***@***.***> wrote:﻿
Can you create a test program and put it on a backup tape?

**Comment by larsbrinkhoff** [comment]
I pointed out some things to @rcornwell on IRC which seems to have lead to finding a problem in the emulator.

**Comment by rcornwell** [comment]
I think I might have solved this, but a test program would be helpful. I am very surprised diagnostics did not catch this. But it appears to have fixed CC on Tops 20.

**Comment by jeffgunter** [comment]
this is a user mode tops10 program to demonstrate.

inline and attached.

-jfg


        title   owp

owp:    jfcl
        reset

        move    2,[710004,,53
[owp.mac.txt](https://github.com/rcornwell/sims/files/12775397/owp.mac.txt)
163]
        seto    1,
        adjbp   1,2
        came    1,[710004,,53163]
        jrst    [outstr [asciz .changed.]
                exit]
        outstr  [asciz .no change.]
        exit

        end     owp

**Comment by rcornwell** [comment]
Pushed out a patch that should fix it.

**Comment by jeffgunter** [comment]
i agree that my exec mode tops10 monitor code now works again. 

however, i would note that the sc40 and klh10 allow the use of adjbp and owgbp even if the pc is running in section zero.  i am almost certain the same was true for our kl10.

the klh10 comments in  inbyte.c support my claim.  the user mode demo program owp.mac.txt above runs on klh10 but fails even under the new simh.  i'm not sure it is critical to me, as long as the kernel nzs code works, which it apparently does.  i do have a couple of programs that use it in user mode from section 0, but i can live without or fix them to run in nzs.

-jfg

**Comment by rcornwell** [comment]
KLH10 is really a KN10 not a KL10B. According to the 1982 Processor Ref (page 2-85),
  "In section 0 the pointer is always of the above type (normal word) -- local and one word --- and P must be <= 36."

I will check the KL10 microcode tomorrow and see if it would handle OWGBP in section 0 but I think it will not.

**Comment by larsbrinkhoff** [comment]
KN10 isn't supposed to diverge in essentials from KL10B.

Here's a comment from KLH10 inbyte.c:

```
* The PRM claims that one-word global BPs are only legal in non-zero sections.
  More recent info (Uhler) indicates they are now legal in all sections, altho
  two-word BPs are still only valid in non-zero section contexts.
  SO: Can OWGBPs in section 0 use global addresses and access memory in other
  sections?
        [Assuming yes.]
```

**Comment by rcornwell** [comment]
I pushed a fix to allow owgpb to be valid in section 0, along with fixes to allow same for extend instructions. Running testing now.

**Comment by rcornwell** [comment]
Is this working?
