### ISSUE TITLE
KA10: 0/ PUSH

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#35]
Here's a riddle.  What happens if you put `PUSH` in location 0 and then execute it?

The answer is that it writes a new `PUSH 0,0` instruction to location 1, and then executes that.  Now it's more interesting, because it writes `PUSH 0,1(1)` to location 2.

And so on, but when it hits location 20, it breaks.  If I single step this in timesharing DDT, location 20 gets 0.  If I single step in SIMH, it gets 000000000022.  The correct value ought to be `PUSH 0,17(17)`.

**Comment by larsbrinkhoff** [comment]
DDT single stepping shows the same failure in three simulators (this one, stock SIMH, and KLH10), so I think that's a DDT or ITS bug.

**Comment by larsbrinkhoff** [comment]
If I start the simulator without any configuration, deposit the PUSH instruction to location 0, and single step, the transision from 17 to 20 works.  It hangs at 23, but I think that's expected.

If I start timesharing DDT in ITS and deposit PUSH to location 0, set a breakpoint at 0 in SIMH, and jump to 0, then the contents of location 20 is incorrect.

**Comment by larsbrinkhoff** [comment]
If I do the timesharing thing and jump to 0 without setting any breakpoints, the program works.

Aren't SIMH breakpoints and single stepping invisible to the target?

**Comment by rcornwell** [comment]
Not is sure what is going on here, however the KA10 and KI10 pass all CPU diagnostics without any issues. ISTR there are some issues with floating point reliability testing.

**Comment by larsbrinkhoff** [comment]
Here's a step by step description of how to reproduce:

1. Create a job: `x$j`
2. Deposit a push instruction: `0/ push`
3. Type Control-E to set a breakpoint: `break 0` and continue with `c`.
4. Start the program: `0$g`.
5. The breakpoint will trigger.  Single step until the PC becomes 20.
6. Contents at 20 is LUUO00 0,22.  Expected is PUSH 0,17(17).

**Comment by rcornwell** [comment]
This might have something to do with the fact that the AC's are not stored in the same place as memory. This could be an artifact of how ITS handles context switching.
