### ISSUE TITLE
KA10: COMPLR doesn't work

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#37]
When I start COMPLR, there's no `_` prompt:

    *:complr
    
    LISP COMPILER 2155 [in LISP 2154]

If I press Enter, there's an error message and the prompt is displayed:

    INCORRECT COMMAND SYNTAX - MAKLAP
    _

Now I should be able to compile Lisp files, but the program doesn't seem to be doing anything after entering the command line:

    _liblsp;_libdoc;tty

It's still possible to enter text.

**Comment by larsbrinkhoff** [comment]
Successful run in KS ITS:

```
*:complr

LISP COMPILER 2155 [in LISP 2154]

_liblsp;_libdoc;tty

_

**Comment by larsbrinkhoff** [comment]
@eswenson1, do you know a better way to debug this, than putting PRINC statments into COMPLR to see what it's doing?

**Comment by eswenson1** [comment]
I'd recommend this:

* load COMPLR
* Type ^G
* (load "liblsp;dbg fasl")
* (debug t)
* (maklap)

Then, assuming it does the same thing and you don't get a prompt and it won't compile anything:

* type ^B (to force a breakpoint)
* type (debug) (to enter the debugger)
* look around (v will give a nice backtrace, e will evaluate expressions, u/d to move up/down stack, ? for help).

**Comment by rcornwell** [comment]
It is doing an XCT 11 of a MUUO, this could not be setting things correctly in the fault registers. There is some question about when exactly OPC gets updated and when it does not.

**Comment by larsbrinkhoff** [comment]
Great, Eric. Thank!

@lokedhs Can you incorporate these debugging tips in the Maclisp hello world?

**Comment by rcornwell** [comment]
This appears to be working.

**Comment by larsbrinkhoff** [comment]
I'm running tests.

**Comment by larsbrinkhoff** [comment]
We're good.
