### ISSUE TITLE
KA10: EMACS won't load libraries

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#38]
When building EMACS, some essential libraries are first generated from TECO sources.  This is done with the EINIT library.  It should be run from EMACS with `M-X Run Library$EINIT$? Generate`.  However, this elicits the message

    LIB     FILE NOT IN LIBRARY FORMAT?

This message comes from EMACS1; USRCOM 514 file; Load Library function.  Of course, it's TECO code, so it's nearly impossible to decipher.

I dumped out the EMACS; EINIT :EJ file from ITS, and confirmed that it's identical to the one in the its repository.  So there's no corruption.

**Comment by larsbrinkhoff** [comment]
Oops, compared against the wrong file.

**Comment by larsbrinkhoff** [comment]
There's a difference in TECO.  In the KS build, the value of the NAMFLG symbol (from SYSENG; LFN) is 400000000000.  In the KA build, it's 0.  The latter must be wrong, because in the source it's

    NAMFLG==:1_35.

**Comment by larsbrinkhoff** [comment]
I made a small program with that statement, and indeed the symbol comes out defined as 0.

**Comment by larsbrinkhoff** [comment]
Something with the ASHC instruction.  DDTing MIDAS:

    BAKAR+13>>ASHC AA,(B)   b[   43   aa[   0   a[   1   aa=1   a=2   ^N
    BAKAR+14>>LSH A,1   aa[   0   a[   0

Before ASHC, AA (AC1) is 0, A (AC2) is 1, and B is 43.  After, AA is 0 and A is 0.

Somehow the 1 in A is lost.  It should go to AA.

![ashc](https://user-images.githubusercontent.com/775050/35859603-0d9ec0ee-0b41-11e8-89f6-4a055258b319.png)

**Comment by larsbrinkhoff** [comment]
I checked all libraries included in binary form in the image build.  None of them could be loaded.  So it's not just EINIT.

The loading is done with the `Load Library` function in EMACS1; USRCOM.  There's a comment:

    !* File is good if it starts with a pure string,!
    !* whose length is length of file.!

My theory is that this test fails.

**Comment by larsbrinkhoff** [comment]
The TECO code for this is:

    q.1fp-100"e
        q.1+fq.1+4-(q0*5120+400000000000.)"e

So if I have my TECO right, `q.1fp` minus 100 must be zero, and `q.1+fq.1+4` minus `q0*5120+400000000000` must also be zero.

**Comment by larsbrinkhoff** [comment]
Notes about TECO.

`q<x>` returns the Q register <x>.  In this case, the name of the register is `.1`.

`<x>FP` returns a number describing the type of <x>.  `100` is a pure string.

`+` and `*` are the conventional arethmetic operators.

`FQ<x>` returns the number of characters in <x>.

**Comment by larsbrinkhoff** [comment]
From TECORD:
> A string containing <n> characters takes up <n>+4 consecutive characters in TECO.

So I'm deducing that `q.1+fq.1+4` is the starting address of the string, plus the number of characters in the string, plus 4.

**Comment by larsbrinkhoff** [comment]
> Numbers which are pointers are decoded by subtracting 400000000000 octal (the smallest negative integer) to get a character address.

**Comment by larsbrinkhoff** [comment]
The function stores `FS :EJ PAGE` in Q-reg 0.
> FS :EJ PAGE^[   is the number of the lowest page used by :EJ'd shared pure files.  Initially 256.  If multlipied by 5*1024, and then added to 400000000000 (octal) the result is a suitable string pointer to the last file :EJ'd.

**Comment by larsbrinkhoff** [comment]
I tested these computations in the EMACS minibuffer.  E.g. typed `$$`, entered some expressions with `\` at the end to insert the result into the buffer, end with `$$`.  The results seemed correct.

**Comment by larsbrinkhoff** [comment]
Yes, I'm working on this!

Now that I can see what I'm doing in EMACS with working escape sequences, it's a lot easier.

**Comment by larsbrinkhoff** [comment]
So I have been using the debug facilities.

Pressing `?` when there's an error, you get some interesting capabilities.  I get a TECO backtrace.  I can see the code that was running when the error was raised.  Indeed it's the code that verifies the contents of the library file.

I can view the contents of Q registers in the context of the error.  They all look fine.

**Comment by rcornwell** [comment]
Ok... then why is it triggering an error?

**Comment by larsbrinkhoff** [comment]
I don't know.  I'm viewing the state of EMACS and TECO at the point of the error, but so far I don't see anything wrong.

Since there's a multiplication involved, I have set a breakpoint at TIMES in TECO.  But it doesn't seem to trigger when I run M-X Load Library.  That's strange.  Maybe I'm barking up the wrong tree, or at least the wrong branch.

**Comment by larsbrinkhoff** [comment]
Making notes here.  I don't have the root cause, but maybe some progress.

Since TIMES isn't called, I'm looking at `q.1fp-100` instead.  In case it isn't obvious, this subtracts 100 from the type of the object in Q-register `.1`.

The TECO routine FDATTY implements the FP function which returns a numeric type code.  I expected it to return 100, but it doesn't.  It returns -3, which isn't good.  The cause seems to be that the ILDB instruction at FDATT2+1 returns something unpalatable.

To be continued...

**Comment by rcornwell** [comment]
Do you know if ILDB is faulting or not?

**Comment by larsbrinkhoff** [comment]
No I don't know.  I'm debugging this in the regular DDT.

**Comment by rcornwell** [comment]
Ok... want to make sure that I have trap handling for ILDB and IDPB correct, these are two instructions on KA10.

**Comment by larsbrinkhoff** [comment]
This doesn't look right.  The byte pointer is 10700661777 before ILBD, and 260700662000 after.

```
FDATT2+1>>ILDB B,BP   B/   -1,,FCMD   BP/   RRSYNC+12,,661777      bp[   10700661777   ^N
FDATT2+2>>CAIN B,DISBUF+1   B/   0      bp[   260700662000

**Comment by larsbrinkhoff** [comment]
To get to the above point, do

```
:emacs
M-X load$einit^Z
$^K FDATT2$B $P

**Comment by larsbrinkhoff** [comment]
Confirmed.  EMACS will now load libraries.  I think this issue can be closed.

**Comment by larsbrinkhoff** [comment]
There really isn't a new [PURE] file, so the build breaks.  But that shouldn't be due to a problem in the simulator.

**Comment by rcornwell** [comment]
This appears to be working.

**Comment by larsbrinkhoff** [comment]
Yes.
