### ISSUE TITLE
Unable to build KI10 simulator

### ISSUE THREAD

**Issue by b4** [rcornwell/sims#4]
lib paths are: /usr/lib /usr/X11/lib
include paths are:  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include
using libm: /usr/lib/libm.dylib
using libpthread: /usr/lib/libpthread.dylib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/pthread.h
using regex: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/regex.h
using libdl: /usr/lib/libdl.dylib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/dlfcn.h
using mman: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/sys/mman.h
***
*** ki10 Simulator being built with:
*** - compiler optimizations and no debugging support. Apple LLVM version 8.0.0.
***
gcc -std=c99 -U__STRICT_ANSI__  -O2  -DSIM_COMPILER="Apple LLVM version 8.0.0" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_REGEX_H -DHAVE_DLOPEN=dylib -DHAVE_GLOB -DHAVE_SHM_OPEN  PDP10/ka10_cpu.c PDP10/ka10_sys.c PDP10/ka10_df.c PDP10/ka10_dp.c PDP10/ka10_mt.c PDP10/ka10_cty.c PDP10/ka10_lp.c PDP10/ka10_pt.c PDP10/ka10_dc.c PDP10/ka10_rp.c PDP10/ka10_rc.c PDP10/ka10_dt.c PDP10/ka10_dk.c PDP10/ka10_cr.c PDP10/ka10_cp.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -DKI=1 -DUSE_INT64 -I PDP10 -DUSE_SIM_CARD -o BIN/pdp10-ki -L/usr/X11/lib -lm -lpthread -ldl
PDP10/ka10_cpu.c:3523:65: warning: '&&' within '||' [-Wlogical-op-parentheses]
              if (!pi_cycle && ((FLAGS & (USER|USERIO)) == USER &&
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
PDP10/ka10_cpu.c:3523:65: note: place parentheses around the '&&' expression to silence this warning
              if (!pi_cycle && ((FLAGS & (USER|USERIO)) == USER &&
                                                                ^
PDP10/ka10_cpu.c:1787:20: error: use of undeclared label 'unasign'
              goto unasign;
                   ^
1 warning and 1 error generated.

Building GCC to see if it behaves the same.

**Comment by rcornwell** [comment]
I just pushed out an update see if that works. If you have problems with the KI you might try setting KI_22BIT to 0. This will turn all controllers from DF10C controllers to DF10 controllers. And limit memory to 256kw.

**Comment by b4** [comment]
Builds now.
