### ISSUE TITLE
KA10: crash setting cpu 512k

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#41]
As of 9c151f905b62d3589330015005fc02ed4691122d.

Steps to repeat:

1. `make ka10`
2. Start `ka10`
3. Enter `set cpu 512k`
4. Segmentation fault

**Comment by larsbrinkhoff** [comment]
The previous commit doesn't suffer this problem.

**Comment by rcornwell** [comment]
I am unable to reproduce this.

**Comment by rcornwell** [comment]
This is fixed. Sorry wrong initial memory size setting.
