### ISSUE TITLE
PDP-6: Type 166 arithmetic processor

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#45]
Starry-eyed wish item.

**Comment by larsbrinkhoff** [comment]
Available software:

- MACDMP
- TECO6
- MIDAS 6

**Comment by larsbrinkhoff** [comment]
Standalone binaries, unknown if they are for PDP-6:

- TECO
- STINK
- MIDAS

**Comment by larsbrinkhoff** [comment]
```
<kiteguy> TINY 4S47   DEC PDP-6 #2 6-3-69 MONITOR JUST LOADED
```

Suppose we can close this soon.  Good job! :-)

**Comment by rcornwell** [comment]
Support is in current commit.

**Comment by larsbrinkhoff** [comment]
I haven't tested this yet, but I assume you have.  I think this can be closed now, and if problems appear new issues can be opened.
