### ISSUE TITLE
KA10: TOP LEVEL INTERRUPT 200 

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#48]
Shortly after booting ITS, there's the message

```
TOP LEVEL INTERRUPT 200 DETACHED JOB # 3, USR:TARAKA CNAVRL

**Comment by larsbrinkhoff** [comment]
I believe 200 is %PIVAL.  ".VALUE INSTRUCTION EXECUTED"

**Comment by larsbrinkhoff** [comment]
TARAKA CNAVRL is the job which starts COMSAT.  I'm going to close this on the assumption that COMSAT is displeased with the lack of networking in KA ITS.

**Comment by rcornwell** [comment]
It appears that this might be related to the fact that the interval timer has not stabilized yet.

**Comment by larsbrinkhoff** [comment]
Maybe I was too quick to close this.  We can reopen it if there's more information.

**Comment by rcornwell** [comment]
If it is what I think it is, there is not much I can do to fix it.

**Comment by larsbrinkhoff** [comment]
It calls UDEATH, which means it's doing a controlled shutdown.

**Comment by rcornwell** [comment]
Looking at code it clears the clock interrupt, does some stuff and then checks if the interrupts are clear. But in the time it was off doing things several clock interrupts get posted.

**Comment by larsbrinkhoff** [comment]
Now we do have networking, but CNAVRL still dies the same way.

**Comment by rcornwell** [comment]
This might be related to the interrupt issues I have been trying to debug.

**Comment by rcornwell** [comment]
This error might be fixed with the addition of the IMP. I don't see it on my current system.

**Comment by larsbrinkhoff** [comment]
So it may be that COMSAT wants to have the IMP, i.e. NCP or TCP/IP, available.

**Comment by rcornwell** [comment]
Now that we have networking, can you figure out why this bug is still occurring?

**Comment by larsbrinkhoff** [comment]
I don't think it's a bug in the simulator.  "INTERRUPT 200" is because .VALUE was executed.  This is just software, not hardware interrupts.

**Comment by larsbrinkhoff** [comment]
I'm closing this.  I can reopen if I see it's a simulator issue.
