### ISSUE TITLE
MIT KA10 pager

### ISSUE THREAD

**Issue by aap** [rcornwell/sims#5]
Have you seen this document about the MIT pager?
https://github.com/PDP-10/its/blob/master/doc/ITS_Hardware_Memo_2.pdf
Hopefully ITS can again run on a KA with that pager implemented.

**Comment by rcornwell** [comment]
Yes I have, thanks. Right now I need to get the KI10 to boot correctly with more then 256Kw of memory. Then I can move on to put ITS on the KA10.

**Comment by rcornwell** [comment]
The latest commit should have a complete ITS pager. Whether it works correctly or not, I don't know. What I need is a ITS system to test it with. I believe that the DM system is closest to a standard KA10.

**Comment by larsbrinkhoff** [comment]
Hey @aap,

We're now testing this heavily.  It seems to be coming along nicely.  ITS is booting and starting the first DDT instance.  It's paging away happily for a while.

**Comment by rcornwell** [comment]
I believe that the ITS pager is working, so I am closing this issue.
