### ISSUE TITLE
TYPE340 display doesn't build under OS X

### ISSUE THREAD

**Issue by b4** [rcornwell/sims#50]
1 warning generated.
display/x11.c:51:10: fatal error: 'X11/X.h' file not found
#include <X11/X.h>
         ^~~~~~~~~
1 error generated.

X11/X.h is found in /opt/X11, not /usr/X11 or similar

**Comment by b4** [comment]
Builds successfully with `make ka10 TYPE340=y CFLAGS_G="-I/opt/X11/include"`

**Comment by rcornwell** [comment]
Can we close this issue?

**Comment by larsbrinkhoff** [comment]
I haven't tested this, but @b4 seems happy.
