### ISSUE TITLE
KA10: crash when run without X11

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#51]
This should be an issue with @philbudne's 340 emulator.

If I boot DSKDMP and start e.g. the standalone @ TECO available in the ITS . directory, the simulator crashes with a segfault.  Gdb says this happens in XkbSetDetectableAutoRepeat.

If I `set dpy disable`, this doesn't happen.

**Comment by philbudne** [comment]
It's crashing a call I just added, with a NULL dpy pointer.
I'd be surprised if any of the following calls would be any happier!

The display code as integrated into mainline SimH doesn't use x11.c,
it uses sim_ws.c

In any case, I'll submit fixes "upstream" in the SimH repo.

The SimH repo PDP1 integration creates (or tries to create) the
display window when "set dpy enable" is given (and displays an error
if it can't) perhaps the PDP6/10 integration should do the same??

Phil

**Comment by larsbrinkhoff** [comment]
Ideally I'd like the window to open automatically when an application (standalone or timesharing) starts using the display.  I think that's roughly how it works now?  This is convenient for many users who won't be using graphics.

**Comment by rcornwell** [comment]
@philbudne Whenever you need me to pull something down from the main stream just let me know. I tend to update periodically. Whenever I see that there is needed patches.

**Comment by larsbrinkhoff** [comment]
@philbudne,
Something strange just happened.  I'm experimenting wich ITS "channel 1 multiplexing" which makes PI channel 1 interrupts go to other locations than 42.  When I tried to use magtape, the Type 30 window popped up!

Sorry, not the best bug report.  Just maybe something to consider.

**Comment by philbudne** [comment]
I've been thinking the window should appear when "set dpy enable" is
issued, both because that's what the PDP-1 sim does, and because "you
just never know when the first display reset will be executed"

**Comment by larsbrinkhoff** [comment]
That's fine.  It's a minor issue.

**Comment by larsbrinkhoff** [comment]
This is now fixed in mainline SIMH.
