### ISSUE TITLE
KA10: PI channel 1 multiplexing

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#55]
I'm opening a separate issue for this.

I seem to have this working, but I'm not sure how to best implement it.

**Comment by larsbrinkhoff** [comment]
I changed `set_interrupt` to accept interrupt levels 0-15, with 8-15 being the multiplexed channels.  I had to go through all devices to ensure they mask with 7.

However, I don't know how you want 8-15 handled in set_interrupt.  Currently, I have this:

```
void set_interrupt(int dev, int lvl) {
    if (lvl > 7 || lvl == 1) {
        pi_loc = (040 + 2*lvl);
        lvl = 1;
        lvl &= 07;
    }

    if (lvl) {
        dev_irq[dev>>2] = 0200 >> lvl;
        pi_pending = 1;
        sim_debug(DEBUG_IRQ, &cpu_dev, "set irq %o %o\n", dev & 0774, lvl);
    }
}
```

But I suppose you would want the global pi_loc gone.  Do you want to add a new set of bits in dev_irq for 8-15?

**Comment by larsbrinkhoff** [comment]
You also said you wanted the devices to get their PI channel something like this, right?

    set kaimp mpx 4 # also 5
    set dt mpx 6
    set mta mpx 7

**Comment by rcornwell** [comment]
This is working in current patch. 

set cpu mpx
set mta mpx=7
set dt mtx=6
