### ISSUE TITLE
KA10: Testing DECtape in ITS

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#62]
Opening an issue to log my attempts to use DECtape in ITS.

> Since microtapes are hardwarily and softwarily unreliable on the ITS systems, their use is discouraged.

.INFO.; DDT 33

**Comment by larsbrinkhoff** [comment]
I build stock ITS with NEWDTP==1 and NUNITS==1.  No channel 1 multiplexing.

I attached an empty file to dt0 and enabled all debug flags.

In ITS, I typed `:assign 1`, and then `^F`.  I got this:

```
DBG(5527048639)> DT CONO: DTA 323 CONO 231212 PC=34634
DBG(5527048642)> DT CONO: DTB 327 CONO 770000 PC=34635 DTSB=770000000000
DBG(5527049640)> DT DETAIL: DTA 1 start 000200
DBG(5527089640)> DT DETAIL: DTA 1 forward end
DBG(5527189641)> DT DETAIL: DTA 1 forward block 0000
DBG(5527189667)> DT DATAIO: DTA 320 DATI 000000000000 PC=034111
DBG(5527189760)> DT CONO: DTA 323 CONO 241202 PC=34160
DBG(5527189763)> DT CONO: DTB 327 CONO 770001 PC=34161 DTSB=770001000000
DBG(5527219642)> DT DETAIL: DTA 1 forward check
Segmentation fault

**Comment by larsbrinkhoff** [comment]
ITS number DECtape units starting from 1.

**Comment by larsbrinkhoff** [comment]
Also tried `:uinit` to write an empty file directory.  Same result as above.

**Comment by larsbrinkhoff** [comment]
Also tried to attach a real DECtape image to dt0.  No change in behaviour.

**Comment by rcornwell** [comment]
This is now working.
