### ISSUE TITLE
KA10: .DSTART crash

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#64]
The test program below will reliably crash ITS in one of two ways.  If run directly, ITS will hang.  If run under DDT, here's a BUGHLT.

The display list passed to .DSTART is actually wrong.  But I don't think that should crash ITS.

```
a==1
p==17

go:     .dstart [-dlen,,dlist-1]
         .lose
        movei a,5*30.
        .sleep a,
        .logout 1,

dlist: 373737,,3000    ;Escape, Stop
dlen=.-dlist

end go

**Comment by larsbrinkhoff** [comment]
CC @philbudne on this.  (There's no new information in this issue since I last posted about this.)

**Comment by larsbrinkhoff** [comment]
Hmmm, now I can't get the BUGHLT from DDT.  But I *think* it looked like this:

```
UUO WITH PI IN PROGRESS  
PI LEVEL 6 BUGHALT.  FIND A WIZARD OR CONSIDER TAKING A CRASH DUMP.

**Comment by larsbrinkhoff** [comment]
Apparently there's something about the argument to .DSTART.

- If the BLKO pointer has a small negative number in the left half, ITS is prone to crash.
- If it's something like `DLIST-2000`, it's ok (this is copied from PDSET).
- I tested -2000, and got a DPY interrupt (but no crash).

**Comment by larsbrinkhoff** [comment]
I have compared a "small negative number" run against "dlist-2000".  Everything seems to go well until the 340 interrupt service routine calls LPTRT1 to exit.  When the JRST 12, instruction is executed, the 340 is supposed to interrupt but it doesn't.  Instead ITS goes into the idle 17/ AOJA 17 loop from which it never returns.

**Comment by larsbrinkhoff** [comment]
CLKTIC isn't called.

I see console TTY interrupts are executed.

**Comment by larsbrinkhoff** [comment]
Here's a log with CPU DEBUG=IRQ.
[irq.log](https://github.com/rcornwell/sims/files/2136692/irq.log)

**Comment by larsbrinkhoff** [comment]
From this passage, I think dpy_svc raises an interrupt (that line is my own addition).

Then the interrupt is serviced several times.  It doesn't look like DPY is clearing the interrupt.  Maybe that's wrong, or maybe it's intentional.

Then dpy_update_status raises an interrupt.  At this point, there already is an interrupt active, so "set irq" says PIH is 002.

Then the interrupt is cleared.  There is now a TTY interrupt pending (010).

Next the TTY interrupt is serviced a few times.  However, after this we're stuck in a state where PIH is 002.

```
dpy_svc: interrupt^M
DBG(726761316)> CPU IRQ: set irq 130 6 177 000 000^M
DBG(726761317)> CPU IRQ: trap irq 6 000 000 ^M
DBG(726761341)> CPU IRQ: restore irq 2 002^M
DBG(726761343)> CPU IRQ: trap irq 6 000 000 ^M
DBG(726761348)> CPU IRQ: restore irq 2 002^M
DBG(726761350)> CPU IRQ: trap irq 6 000 000 ^M
DBG(726761355)> CPU IRQ: restore irq 2 002^M
DBG(726761357)> CPU IRQ: trap irq 6 000 000 ^M
DBG(726761362)> CPU IRQ: restore irq 2 002^M
DBG(726761364)> CPU IRQ: trap irq 6 000 000 ^M
DBG(726761369)> CPU IRQ: restore irq 2 002^M
DBG(726761371)> CPU IRQ: trap irq 6 000 000 ^M
DBG(726761376)> CPU IRQ: restore irq 2 002^M
DBG(726761378)> CPU IRQ: trap irq 6 000 000 ^M
DBG(726761383)> CPU IRQ: restore irq 2 002^M
DBG(726761385)> CPU IRQ: trap irq 6 000 000 ^M
DBG(726761390)> CPU IRQ: restore irq 2 002^M
DBG(726761392)> CPU IRQ: trap irq 6 000 000 ^M
DBG(726761397)> CPU IRQ: restore irq 2 002^M
DBG(726761399)> CPU IRQ: trap irq 6 000 000 ^M
DBG(726761404)> CPU IRQ: restore irq 2 002^M
DBG(726761406)> CPU IRQ: trap irq 6 000 000 ^M
DBG(726761411)> CPU IRQ: restore irq 2 002^M
DBG(726761413)> CPU IRQ: trap irq 6 000 000 ^M
dpy_update_status: interrupt^M
DBG(726761418)> CPU IRQ: set irq 130 4 177 000 002^M
DBG(726761422)> CPU IRQ: trap irq 4 010 002 ^M
DBG(726761571)> CPU IRQ: clear irq 130^M
DBG(726761622)> CPU IRQ: restore irq 10 012^M
DBG(726767434)> CPU IRQ: set irq 120 3 177 000 002^M
DBG(726767435)> CPU IRQ: trap irq 3 000 002 ^M
DBG(726767670)> CPU IRQ: clear irq 120^M
DBG(726767714)> CPU IRQ: restore irq 20 022^M
DBG(726777673)> CPU IRQ: set irq 120 3 177 000 002^M
DBG(726777674)> CPU IRQ: trap irq 3 000 002 ^M
DBG(726777910)> CPU IRQ: clear irq 120^M
DBG(726777954)> CPU IRQ: restore irq 20 022^M
DBG(726787912)> CPU IRQ: set irq 120 3 177 000 002^M
DBG(726787913)> CPU IRQ: trap irq 3 000 002 ^M
DBG(726788148)> CPU IRQ: clear irq 120^M
DBG(726788192)> CPU IRQ: restore irq 20 022^M
DBG(726798151)> CPU IRQ: set irq 120 3 177 000 002^M
DBG(726798152)> CPU IRQ: trap irq 3 000 002 ^M
DBG(726798387)> CPU IRQ: clear irq 120^M
DBG(726798431)> CPU IRQ: restore irq 20 022^M
DBG(726806966)> CPU IRQ: set irq 4 7 177 000 002^M   
DBG(726808391)> CPU IRQ: set irq 120 3 177 000 002^M
DBG(726808392)> CPU IRQ: trap irq 3 000 002 ^M
DBG(726808628)> CPU IRQ: clear irq 120^M
DBG(726808674)> CPU IRQ: restore irq 20 022^M
DBG(726990417)> CPU IRQ: set irq 4 7 177 000 002^M
DBG(727173865)> CPU IRQ: set irq 4 7 177 000 002^M
DBG(727357313)> CPU IRQ: set irq 4 7 177 000 002^M
DBG(727540761)> CPU IRQ: set irq 4 7 177 000 002^M

**Comment by larsbrinkhoff** [comment]
Since a DPY DATAO does call clr_intrerupt, interrupts are delivered back-to-back.  From this comment in ka10_dpy.c it looks like the intent is there should be 50 microseconds between interrupts.

```
/*
 * number of (real?) microseconds between svc calls
 * used to age display, poll for WS events
 * and delay "data" interrupt
 * (VB10C could steal cycles)
 */
#define DPY_CYCLE_US    50
  
/*
 * number of DPY_CYCLES to delay int
 * too small and host CPU doesn't run enough!
 */
#define INT_COUNT       (500/DPY_CYCLE_US)

**Comment by larsbrinkhoff** [comment]
I inserted a few calls to clr_interrupt, but ITS still hangs like before.

**Comment by larsbrinkhoff** [comment]
Closing in...

First there's a normal data interrupt at level 6.  It's serviced by a BLKO and is dismissed fine.

Then there's a second data interupt.  Before it has been dismissed, there's a special interrupt at level 4.  Most likely because of a 340 STOP word at the end of the display list.  This interrupt is higher priority, so the service routine is run.  The data interrupt is held as 002 in PIH.

The special interrupt is dismissed, so PIH goes back to 002.  However, the data interrupt is never dismissed.  There's no "restore irq 2".  So PIH is stuck at 002.

Now there can be no more clock interrupts, because they are at level 7.

```
dpy_svc: interrupt
DBG(1714053391)> CPU IRQ: set irq 130 6 177 000 000
DBG(1714053392)> CPU IRQ: trap irq 6 000 000
dpy_update_status: clear interrupt
DBG(1714053397)> CPU IRQ: clear irq 130
dpy_update_status: clear interrupt
DBG(1714053397)> CPU IRQ: clear irq 130
DBG(1714053397)> CPU IRQ: restore irq 2 002

dpy_svc: interrupt
DBG(1714058779)> CPU IRQ: set irq 130 6 177 000 000
DBG(1714058780)> CPU IRQ: trap irq 6 000 000
dpy_update_status: clear interrupt
DBG(1714058785)> CPU IRQ: clear irq 130

dpy_update_status: interrupt
DBG(1714058785)> CPU IRQ: set irq 130 4 177 000 002
DBG(1714058789)> CPU IRQ: trap irq 4 010 002
CONO: clear interrupt
DBG(1714058928)> CPU IRQ: clear irq 130
dpy_update_status: clear interrupt
DBG(1714058928)> CPU IRQ: clear irq 130
DBG(1714059122)> CPU IRQ: restore irq 10 012

dpy_svc: interrupt
DBG(1714070577)> CPU IRQ: set irq 130 6 177 000 002

DBG(1714197334)> CPU IRQ: set irq 4 7 177 000 002
DBG(1714376909)> CPU IRQ: set irq 4 7 177 000 002
DBG(1714556484)> CPU IRQ: set irq 4 7 177 000 002
DBG(1714736059)> CPU IRQ: set irq 4 7 177 000 002
DBG(1714915635)> CPU IRQ: set irq 4 7 177 000 002

**Comment by philbudne** [comment]
It may not have anything to do with the problem, but for the record,
I'm SURE the interrupt behavior of ka10_dpy.c differs from the real
hardware (a PDP-6 interface for which no prints are available).

The behavior of the dpy device code on BLKO/DATAO is to execute BOTH
halfwords as 340 commands, IMMEDIATELY (so long as the LH doesn't halt
the display processor), and set a countdown to trigger a data
interrupt "later" (so that the CPU can do work)!  I don't think the
delay I picked had anything to do with the 340 cycle time, it was just
a value that seemed to work.

A more realistic simulation might be to execute the LH, and save the
RH for execution one 340 cycle time later, and after executing the RH,
schedule a data interrupt one 340 cycle time after that.

**Comment by larsbrinkhoff** [comment]
At least now I understand why the left half of the BLKO pointer matters.  If it's exactly the length of the display list, the special STOP interrupt will coincide with the end of the BLKO pointer.

If I pad out the display list with an extra word after the STOP, there is no crash.

On the other hand, if the BLKO pointer runs out before there's a STOP there's the crash again.

I see the instruction after the BLKO is this strange thing:

    CONO PI,4000+200_<-SDCHN>       ;HACK HACK

I'm not sure how this is supposed to work.

**Comment by larsbrinkhoff** [comment]
Oh, it should raise a special 340 interrupt.

**Comment by larsbrinkhoff** [comment]
@philbudne,

Thanks for clarifying.  I don't think executing both halfwords at once is a big concern.

**Comment by larsbrinkhoff** [comment]
However, the BLKO instructions are executed back-to-back.  This was clearly not your intent.  The reason is that clr_interrupt isn't called.  This means that the device is still flagging an interrupt, even though JEN has dismissed the interrupt.

Right @rcornwell?  The PI system is kind of level triggered?

I will fix this by inserting clr_interrupt in appropricate locations.

**Comment by larsbrinkhoff** [comment]
Instruction trace time!  I added the value of PIH last to each line.

First, this is what happens when ITS sets off the 340 going.  It triggers a special interrupt, and when it's dismisssed, there's a data interrupt.

The data interrupt writes a BLKO instruction to location 54 and JENs.  Since the device is still flagging an interrupt, the BLKO runs right away.

Note how PIH is 002 for the duration of the interrupts.  All is well and good.

```
PC      AC            EA        AR            RES           FLAGS IR
056720  254200000000  000017    010000000017  000000000200  300000  254520056677  JEN @56677 020
000017  254200013623  000017    254200013623  254200013624  010000  344000000017  AOJA 0,17 000
000017  254200013624  000017    254200013624  254200013625  010000  344000000017  AOJA 0,17 000
000017  254200013625  000017    254200013625  254200013626  010000  344000000017  AOJA 0,17 000
000054  254200013626  071334    000000071334  000000071334  010000  264000071334  JSR 0,71334 002
071335  254200000000  071333    254200000000  254200000000  000000  202040071333  MOVEM 1,71333 002
071336  254200000000  117123    713100072367  713100072367  000000  200040117123  MOVE 1,117123 002
071337  713100072367  000054    713100072367  713100072367  000000  202040000054  MOVEM 1,54 002
071340  713100072367  071333    254200000000  254200000000  000000  200040071333  MOVE 1,71333 002
071341  254200000000  000017    010000000017  000000000200  000000  254520071334  JEN @71334 002
000054  254200000000  072367    777775406105  020017220764  010000  713100072367  BLKO 130,72367 002
000017  254200013626  000017    254200013626  254200013627  010000  344000000017  AOJA 0,17 000
000017  254200013627  000017    254200013627  254200013630  010000  344000000017  AOJA 0,17 000
000017  254200013630  000017    254200013630  254200013631  010000  344000000017  AOJA 0,17 000

**Comment by larsbrinkhoff** [comment]
17/ AJOA 17 is the idle loop, by the way.

Next, a single BLKO is executed to service another 340 data interrupt.  Great so far.

```
PC      AC            EA        AR            RES           FLAGS IR
000017  254200025520  000017    254200025520  254200025521  010000  344000000017  AOJA 0,17 000 000
000017  254200025521  000017    254200025521  254200025522  010000  344000000017  AOJA 0,17 000 000
000054  254200000000  072367    777776406106  100200240000  010000  713100072367  BLKO 130,72367 000 002
000017  254200025522  000017    254200025522  254200025523  010000  344000000017  AOJA 0,17 000 000
000017  254200025523  000017    254200025523  254200025524  010000  344000000017  AOJA 0,17 000 000

**Comment by larsbrinkhoff** [comment]
Finally, the BLKO pointer runs out and locatation 55 is executed.

What happens here?  There's a CONO PI instruction to trigger a special 340 interrupt.  PIH is now 012.

```
PC      AC            EA        AR            RES           FLAGS IR
000054  254200000000  072367    777777406107  400000003000  010000  713100072367  BLKO 130,72367 002
000055  254200000000  004010    000000004010  000000004010  010000  700600004010  CONO PI,4010 002
000050  254200002260  070664    000000070664  000000070664  010000  264000070664  JSR 0,70664 012
070665  254200000000  070645    254200000000  254200000000  000000  202040070645  MOVEM 1,70645 012
070666  254200000000  000007    000000000007  000000000000  000000  746700000007  CONSZ 464,7 012
070670  254200002260  070672    254000070672  254000070672  000000  254000070672  JRST 0,70672 012
070672  254200000000  000001    000000000001  400000000646  000000  713240000001  CONI 130,1 012
070673  400000000646  000077    000000000077  000000000077  000000  606040000077  TRNN 1,77 012
070675  254200000000  007400    000000007400  000000000400  000000  713300007400  CONSZ 130,7400 012
070676  400000000646  070764    400000000646  400000000646  000000  321040070764  JUMPL 1,70764 012
070764  400000000646  117113    000002070646  000002070646  000000  200040117113  MOVE 1,117113 012
070765  000002070646  070663    000002070646  000020070664  000000  251040070663  BLT 1,70663 012
070766  254200000000  002000    000000002000  000000000000  000000  713300002000  CONSZ 130,2000 012
070770  254200002260  072302    000000000000  000000000000  000000  335000072302  SKIPGE 0,72302 012
070772  254200000000  005000    000000005000  000000000000  000000  713300005000  CONSZ 130,5000 012
070774  000002070646  072367    000000406110  000000000000  000000  574040072367  HLRE 1,72367 012
```

This goes on for a bit.  The point is that ITS is handling the special interrupt, and PIH remains at 012.

Finally, ITS exits from the interrupt handler with a JEN.  However, PIH doesn't go back to 000 but remains at 002 due to the previous data interrupt.

Since the all-important clock interrupt is at level 7, ITS' scheduler doesn't get to run.

```
PC      AC            EA        AR            RES           FLAGS IR
070712  777777777775  070646    254200000000  254200000000  300000  200100070646  MOVE 2,70646 000 012
070713  070647000003  070645    254200000000  254200000000  300000  200040070645  MOVE 1,70645 000 012
070714  254200000000  000017    010000000017  000000000200  300000  254520070664  JEN @70664 000 012
000017  254200002260  000017    254200002260  254200002261  010000  344000000017  AOJA 0,17 000 002
000017  254200002261  000017    254200002261  254200002262  010000  344000000017  AOJA 0,17 000 002
000017  254200002262  000017    254200002262  254200002263  010000  344000000017  AOJA 0,17 000 002
```

**Comment by larsbrinkhoff** [comment]
So it looks like ITS expects the last BLKO to be auto dismissed, but it's not.  I'll go look in the processor reference manual now...

**Comment by larsbrinkhoff** [comment]
The use of an I/O instruction after the BLKO may be a particularly obscure MIT processor modification!

The *PDP-10 System Reference Manual* says:

> If the instruction in 40 + 2N is a BLKI or BKLO and the count does reach zero, the processor continues to start the interrupt by executing the instruction in location 41 + 2N.  This *cannot* be an IO instruction and the action that results from its execution as an interrupt instruction are those given above for non-IO instruction.
> 
> *CAUTION*
> The execution, as an interrupt instruction, of a CONO, CONI, CONSO or CONSZ in location 40 + 2N or *any* IO instruction in location 41 + 2N hangs up the processor.

**Comment by larsbrinkhoff** [comment]
Clearly ITS does something that's not allowed according to DEC canon.  But then, we know the MIT hackers modified the processor and fixed perceived bugs.  Maybe this was one of them.

If I were to brain storm random theories:

- Maybe the CONO auto dismisses the previous BLKO?
- Or the special interrupt JEN somehow dismisses two interrupts?

**Comment by larsbrinkhoff** [comment]
I got this from Tom Knight:

> I’m not sure of this, so it could be wrong, but it’s OK for the interrupt not to be cleared. The display list is now set up at the higher priority level. When that setup interrupt is cleared, it will immediately take a display data interrupt, which will start the display. That interrupt will be automatically dismissed and things will continue as normal. There might be some trickery having to do with stopping the display when you want to turn it off.

Maybe you Rich can see some detail here I'm missing.

As far as I understand the data interrupt is in progress on channel 6 with PIH = 002.  Then the CONO executes and triggers a special intrerrupt on channel 4.  When this interrupt is dismissed, PIH is again 002 and this should stop all new channel 6 (and 7) interrupts.

**Comment by larsbrinkhoff** [comment]
Tom Knight says it would be quite simple to make changes to have the CONO dismiss the interrupt.  But has no explanation for the apparent absence of CONI bits.

**Comment by larsbrinkhoff** [comment]
I have a possible explanation.  If the processor stays in "second interrupt instruction mode" (I don't know the right term for this according to schematics) when the CONO PI,4010 executes there is a JSR DRECYC at 51.

**Comment by larsbrinkhoff** [comment]
Greenblatt wrote:
> I barely remember this, but it is fairly clear what is going on.
> 
> in IO instructions, most of what would normally be the op code field is used for the device number. so what the hardware is really looking for is just the 7 in the top octal digit. That is present in the CONO, so that is sufficient to dismiss the interrupt.

**Comment by aap** [comment]
All figured out. I documented it here: http://pdp-6.net/asmhacks.html#pisystem

**Comment by larsbrinkhoff** [comment]
And the MIT-AI prints confirm that there was no modification for this.

**Comment by larsbrinkhoff** [comment]
These two RP03 images come with ITS installed: http://lars.nocrew.org/its/nxm/

It you start ITS, and then FED as in #71, ITS will crash or hang.

If you replace 55/ CONO PI,4010 with JSR DRECYC before starting ITS, there will be no crash.  (After loading ITS in DSKDMP, you're in DDT and can do patches.)

**Comment by rcornwell** [comment]
Fixed with interrupt system changes.
