### ISSUE TITLE
KA10: Problem running FED

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#71]
After fixing #64 (through workaround or presumably by allowing the CONO), FED crashes ITS like this:

```
KA: APR ERROR IN NULL JOB  
PI LEVEL 7 BUGPAUSE.  FIND A WIZARD, CONSIDER TAKING A CRASH DUMP,
OR TYPE <ALTMODE>P TO ATTEMPT TO REVIVE THE SYSTEM.
YOU ARE NOW IN DDT.
BUGPC/   CNLJL+2   $Q-2/   CONSZ 230220

**Comment by larsbrinkhoff** [comment]
If I $P at this point, FED may or may not run for a while and then crash again.

**Comment by larsbrinkhoff** [comment]
It seems there's one more piece to the "CONO second interrupt instruction" puzzle.

When the CONO triggers an interrupt on channel 4 (which is were the display special interrupt happens), ITS does a CONI to see if the display caused the interrupt.  But since interrupt was triggered programatically, the 340 status bits doesn't indicate an interrupt.  So ITS doesn't think it needs to be serviced, and quickly JENs back without doing anything.

```
000054  254200000000  072372    777777412074  221676020000  010000  713100072372  BLKO 130,72372  002
000055  254200274541  071121    000000071121  000000071121  010000  264000071121  JSR 0,71121  002
071122  254200000000  004010    000000004010  000000004010  000000  700600004010  CONO PI,4010  002
000050  254200274541  070664    000000070664  000000070664  000000  264000070664  JSR 0,70664  012  
070665  254200000000  070645    254200000000  254200000000  000000  202040070645  MOVEM 1,70645  012
070666  254200000000  000007    000000000007  000000000000  000000  746700000007  CONSZ 464,7  012
070670  254200274541  070672    254000070672  254000070672  000000  254000070672  JRST 0,70672  012
070672  254200000000  000001    000000000001  400000000246  000000  713240000001  CONI 130,1  012
070673  400000000246  000077    000000000077  000000000077  000000  606040000077  TRNN 1,77  012
070675  254200000000  007400    000000007400  000000000000  000000  713300007400  CONSZ 130,7400  012
070677  254200000000  070646    254200000000  254200000000  000000  202100070646  MOVEM 2,70646  012
070700  254200000000  000007    000000000007  000000000000  000000  710700000007  CONSZ 104,7  012
070702  254200274541  070704    254000070704  254000070704  000000  254000070704  JRST 0,70704  012
070704  254200000000  000010    000000000010  000000000000  000000  710300000010  CONSZ 100,10  012
070706  400000000246  070645    254200000000  254200000000  000000  200040070645  MOVE 1,70645  012
070707  254200000000  071123    000000071123  000000000000  000000  254520070664  JEN @70664  012
071123  254200000000  000017    010000000017  000000000200  000000  254520071121  JEN @71121  002
000017  254200274541  000017    254200274541  254200274542  010000  344000000017  AOJA 0,17  000

**Comment by larsbrinkhoff** [comment]
Without the proper handling of the interrupt, everything seems fine for a while.  But in fact, the data interrupts keep coming (since they weren't turned off) and the BLKOs keep execting with an overrun pointer.

This goes on for some time, and then comes the APR ERROR.  I haven't checked this in detail, but I assume it's related to the overrun BLKO pointer.

**Comment by larsbrinkhoff** [comment]
People I asked for information and heard back from:

- [x] Everyone on its-hackers
- [x] Tom Knight
- [ ] David Moon
- [x] Peter Samson
- [ ] Michael Beeler
- [ ] Michael Speciner

**Comment by rcornwell** [comment]
What needs to be done here is that a PIR request while in a PI Cycle needs to execute the second instruction in the requested slot. And dismiss the current held PI request.

**Comment by larsbrinkhoff** [comment]
Agreed.

**Comment by larsbrinkhoff** [comment]
I'll close this since it's really part of #64.

**Comment by rcornwell** [comment]
Fixed with interrupt system changes.
