### ISSUE TITLE
KA10: Full ITS build times out

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#72]

**Comment by larsbrinkhoff** [comment]
Testing different versions of the simulator:

- 7f5a781e2d9b9ddc519d2ff87da180bbbb600adb - times out.

**Comment by larsbrinkhoff** [comment]
This indicates 8167c6344486f4fd319fd6f54a72020064331103 is the culprit.

**Comment by rcornwell** [comment]
8167c63 was requested by you because of issue #68

**Comment by larsbrinkhoff** [comment]
Yes, I remember.

#68 was about getting Daniel Silver's flight simulator to work.  If it's a choice between having the ITS build work, or the flight simulator, I'd rather have ITS.

**Comment by larsbrinkhoff** [comment]
Will test this later:

> Try commenting out lines 118&119 on ka10_cty.c for the current level and see it if works.

**Comment by larsbrinkhoff** [comment]
I reverted the CTY patch as above.  But the build still times out in another part.

I'll try to find the first commit to trigger this.

**Comment by larsbrinkhoff** [comment]
If those two runs doesn't trigger it, maybe do a third:

```
:macsym
(C1) compile_lisp_file(translate_file("share\;eigen >")[2]);
all;

**Comment by larsbrinkhoff** [comment]
Commit b2d468d that previously build fine twice now doesn't any more, so more investigation needed.

**Comment by larsbrinkhoff** [comment]
Looks like *both* the ITS repo commit and the KA10 repo commit affect this.

**Comment by larsbrinkhoff** [comment]
- ITS 15f4c90 + KA10 32c9ebb513cdc6e85678a65102afa27ad85dc149: completes.

**Comment by larsbrinkhoff** [comment]
I think the above establishes that 8167c6344486f4fd319fd6f54a72020064331103 causes the timeout in the Macsyma part of the build scripts.

However, when that's "fixed" (commented out, unclear what the real fix would be), later ITS commits still time out in another part which I'll call "STINK".

- ITS 15f4c90 + KA10 8167c6344486f4fd319fd6f54a72020064331103 + reverted patch - completes.
- ITS 2cb9a10987a520f08a886837a346d12ba6e81643 + KA10 8167c6344486f4fd319fd6f54a72020064331103 + reverted patch - testing...

**Comment by larsbrinkhoff** [comment]
TS STINK is identical in the good (1828e81) and the bad (e4d8240) disk images.

**Comment by rcornwell** [comment]
I believe this is no longer an issue.

**Comment by larsbrinkhoff** [comment]
Agreed.

**Comment by larsbrinkhoff** [comment]
There's another hang right at the beginning when running MAGDMP.  But it only happens occasionally, and only on CircleCI.  Icky.
