### ISSUE TITLE
KA10: Rubin 10-11 external interface

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#75]
Follow up on #74.  This is to talk to some PDP-11s.

The previous pull request implemented the PDP-10 side: intercepting memory accesses to the 3,,000000-3,,777777 range and translating them to Unibus addresses.  Now those accesses need to go outside the KA10 simulator and end up in another process simulating a PDP-11.  Read requests should return data.  Timeouts must be handled.

**Comment by larsbrinkhoff** [comment]
The primary target is @aap's upcoming PDP-11/10 (or 05) with Knight TV hardware.

I think I'd also like to be able to attach SIMH, because it can do GT40, 11/40, and 11/45.

**Comment by larsbrinkhoff** [comment]
Some random ideas for inter-process communication:

- Network socket.
- Subprocess stdio.
- Shared memory.  SIMH does this for the UC15 thing.

**Comment by larsbrinkhoff** [comment]
11LOGO on a 11/45 is interesting, because it had special hardware made by TK to attach eight vector displays.  I think it came before the Knight TV system.

**Comment by larsbrinkhoff** [comment]
I think we can drop the subprocess idea.  It's better to be able to start e.g. SIMH and have full control over the console.

To do this using the SIMH framework, I think there are two options:

- Network, using the sim_tmxr API.
- Shared memory, using the sim_shmem API (in sim_fio.c).

**Comment by larsbrinkhoff** [comment]
sim_shmem API:

- sim_shmem_open (name, size, handle, address)
- sim_shmem_close (handle)
- sim_shmem_atomic_add (pointer, value)
- sim_shmem_atomics_cas (pointer, old, new)

**Comment by larsbrinkhoff** [comment]
The sim_tmxr API, as descibed in sim_tmxh.h, is rather big.  It's geared towards simulating serial lines.  I guess there's a subset of calls that could provide communication between a KA10 and one or more PDP-11.

**Comment by larsbrinkhoff** [comment]
I think a quick and dirty thing with shared memory will be easy to whip up.  I'm quite sure whatever we do, we'll have to change it later so let's go with something simple.

**Comment by aap** [comment]
But then you have to synchronize two processes. A TCP connection would take care of everything for you.

**Comment by larsbrinkhoff** [comment]
I remembered I want to be able to connect, say, a PiDP-11 and a KA10 on another host.  So TCP it is.

**Comment by larsbrinkhoff** [comment]
Fixed by #87.
