### ISSUE TITLE
ITS output to paper tape

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#97]
Hello,

Tested MIDAS output to PTP: again.  ITS will feed the paper tape before, between, and after data blocks.

I compared the output against writing to a file, getting it out of ITS, and converting that to a binary paper tape image.  It's identical except for the zeroes.

**Comment by larsbrinkhoff** [comment]
Attaching fies.  `file-with-zeroes.ptp` comes from PTP, and `file-without-zeroes.ptp` went through magtape.

Here's an "od" of the first file:

```
0000000  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
*
0000040 277 277 261 200 200 200 271 206 200 200 200 260 254 214 240 200 
0000060 200 204 271 207 240 200 200 210 225 240 200 200 200 203 224 210
0000100 211 277 277 276 271 204 271 200 200 210 225 260 211 200 200 210
0000120 225 260 211 200 200 213 236 244 240 200 200 200 231 220 200 200
0000140 200 217 227 200 217 200 200 200 233 217 240 200 200 200 225 242
0000160 200 200 200 201 225 237 240 200 200 203 225 240 200 200 200 202 
0000200  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
*
0000240  \0  \0  \0  \0  \0 277 277 277 200 201 200 225 242 200 200 200 
0000260 200 225 241 276 200 202 201 225 240 200 200 201 200  \0  \0  \0
0000300  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
0000320  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
```
[files.zip](https://github.com/rcornwell/sims/files/2971624/files.zip)

**Comment by larsbrinkhoff** [comment]
Now, loading `files-with-zeroes.ptp` with `load -r` seems to work.  Location 100 has a HALT instruction as expected.

My problem, as I remember it, was that a DSKDMP paper tape written to PTP: didn't work.  Whereas one dumped out with magtape did.  I haven't checked this now.

**Comment by rcornwell** [comment]
The zeros are leader and trailer. This is normal on  a paper tape. Now I can add in a function  to PTR attach that will skip leaders, or to the boot code to skip these.

**Comment by larsbrinkhoff** [comment]
Your PTR seem to handle zeroes right.  I tested `load -r` and `boot ptr` and they boot got HALT into 100.  

I need to check with DSKDMP, which is a much larger program.

**Comment by rcornwell** [comment]
Most of ka10_sys.c is from Bob's PDP10 simulator. I have just made a few minor changes to handle some coverity errors.

**Comment by larsbrinkhoff** [comment]
I just booted DSKDMP assembled directly to PTP:  So I don't see a problem now, and don't remember what problem I had back when I tested this.  Seems fine to me.
