### ISSUE TITLE
KA10: DC line speed and TOPS-10

### ISSUE THREAD

**Issue by pascalgp** [rcornwell/sims#99]
When a line speed is specified for the DC device, TOPS-10 (5.03 and 6.03) hangs during initialization.

**Comment by rcornwell** [comment]
DC10 does not support line speed control. This was set via jumps on the device.

**Comment by pascalgp** [comment]
Setting with 'attach' command in SIMH initialization file. Examples:

```
att dc 1050,speed=300
att dc line=23,1053,speed=300
```

The issue has been introduced with commit "SCP: Updated to current." (da8baebaf7b80350bb02cb218ca9e83fa6d0d8cc) on Jun 21, 2018

Prior to this commit, TOPS-10 completes initialization and the specified 
line speed is honored by SIMH.

**Comment by rcornwell** [comment]
Interesting bug, thanks for catching it. Give me a couple days to figure this out. I have asked Mark if he has any idea. Since he is responsible for SCP changes.

**Comment by rcornwell** [comment]
The current patch should solve the problem.

**Comment by pascalgp** [comment]
Fixed. The monitor now initializes properly. Thank you.
